### ISSUE TITLE
Foot row total have a bug!

### ISSUE THREAD

**Issue by huacnlee** [leikind/wice_grid#10]
My data table had 20 million+ rows,I don't need all row total, because I too slow with count(*) from big tables.

I need a param to set toggle show/hide Row Total.

**Comment by leikind** [comment]
I understand the problem and will see into this. 

And this is not a bug, this is a feature :)

**Comment by leikind** [comment]
Use option :total_entries to initialize_grid to avoid the SELECT COUNT() query: http://github.com/leikind/wice_grid/commit/50b83b170a8bf89725134a2ce8fa78ecc65c280d
