### ISSUE TITLE
has_many :through association

### ISSUE THREAD

**Issue by mostafahussein** [leikind/wice_grid#100]
user has many roles through assignment , how can i show the role of a user in my grid ?

**Comment by leikind** [comment]
Do you mean, in the grid cell? Just like you would do this in the rest of your app.

Please be more specific if this is not the answer

**Comment by mostafahussein** [comment]
I want to show it in a cell like the rest , should i post my models also ?? i want to show the role of every user in a cell , and another question i want to know how to add two values on one cell , like a cell for view profile / edit profile

```
 <%= grid(@users_grid, show_filters: :when_filtered) do |g|
    g.column name: 'ID', attribute: 'id', filter: false
    g.column name: 'Username', attribute: 'user_name'
    g.column name: 'First Name', attribute: 'first_name'
    g.column name: 'Last Name', attribute: 'last_name'
    g.column name: 'E-mail', attribute: 'email'
    g.column name: 'Profile' do |user|
      link_to('View', user_path(user))
    end
    g.column do |user|
      link_to('Delete', method: :delete)
    end
  end -%>

and this is the controller of users

  def index
    @users = User.all
    @users_grid = initialize_grid(User)
  end


```

**Comment by leikind** [comment]
What's inside the column block is pure ruby, the last value of the block is what is rendered  so you are free to write whatever Ruby code you want.

For the filter on roles you have to include this association in `initialize_grid`, and perhaps use `:custom_filter =>` with `:model =>` in the column definition.

**Comment by mostafahussein** [comment]
Can you tell me what should I write because i cant get it from the documentation , what is the code should like ??

**Comment by leikind** [comment]
Here is an example http://wicegrid.herokuapp.com/custom_filters2 . You can see the code right on the page.

The sources of this app are here https://github.com/leikind/wice_grid_examples

**Comment by mostafahussein** [comment]
in your users model i found this line >> has_many :projects, :through => :user_project_participations
where is the example which shows the project values ?

**Comment by leikind** [comment]
there is none I think. But the declaration of the column is the same, the difference would be in the block where you have to show all projects.

Here is some code from another project where a document has many projects:

``` ruby
  g.column name: 'document.field.project_id'._, attribute: 'project_id', model: 'DocumentsProject',
        custom_filter: to_select_with_null(projects_with_deleted_ones_present_in_query(@current_library, @sq), 'document.without_projects'), detach_with_id: 'project-filter' do |rec|
    rec.projects(true).map{|pr|  content_tag(:span, pr.name, :class => "label label-info")  }.join(' ').html_safe
  end
```

`content_tag` is not necessary of course, you can just concatenate it.

the `to_select_with_null` helper returns a hash.

Please mind `rec.projects(true)`  
`true` forces the reload of the association. Why? Well, if document X has projects A, B, C, and you use a filter to only return documents with B, `rec.projects` will return [B] only, so you have to reload the association. Performance-wise this sucks, I know.

And of course :projects should be loaded in `initialize_grid`:  `:include  => [:author, :recipients, :senders, :projects]`

**Comment by mostafahussein** [comment]
looks too complex :S i can make a cell to show the values of has_many belongs_to , but i cant make a cell to show values of has_many :through :S

**Comment by leikind** [comment]
Why do you say so? Yes you can. Do you have an exception? What does your `initialize_grid` look like?

**Comment by mostafahussein** [comment]
the only thing i understand it that , when i wanted to make has_many belongs_to my initialize_grid was this 

``` ruby
@articles_grid = initialize_grid(Article,
                                     :include => [:user])
```

and in the index view was this

``` ruby
g.column name:  'Posted by', attribute: 'user_name', model: 'User', auto_reload: true do |article|
      article.user.user_name if article.user
      end
```

Now in my next case where users has_many :roles :through :assignments i guess my initialize_grid should like this

``` ruby
 @users_grid = initialize_grid(User,
                                     :include => [:assignments],
                                     :include => [:roles])
```

Now in my index view what it should like ??? i cant get this :(

**Comment by leikind** [comment]
Please change

``` ruby
@users_grid = initialize_grid(User,
                                     :include => [:assignment],
                                     :include => [:roles])
```

to 

``` ruby
@users_grid = initialize_grid(User,
                                     :include => [:assignment, :roles])
```

and it should work. Also, learn Ruby better :)

**Comment by leikind** [comment]
``` ruby
@users_grid = initialize_grid(User,
                                     :include => [:assignment, :roles])
```

is the same as

``` ruby
@users_grid = initialize_grid(User,
                                     {:include => [:assignment, :roles]})
```

where

``` ruby
 {:include => [:assignment, :roles]} 
```

is a hash, and hashes have unique keys, so 

``` ruby
{:include => [:assignment],  :include => [:roles]}
```

does not make sense

**Comment by leikind** [comment]
no offence :)

**Comment by mostafahussein** [comment]
okay my problem in the view i wrote it like this g.column name:  'Role', attribute: 'name', model: 'Role', auto_reload: true do |user|
      user.roles.name if user.roles
    end
it displays the word 'Role' 
Note in my console i can get the role of a user using user.roles.pluck(:name)

**Comment by leikind** [comment]
`user.roles` returns an array. What do you expect when you call method `name` on an array? You have to call `name` on each element in this array, and then you have to join these strings together. You can see how I do this with `map` in a previous comment https://github.com/leikind/wice_grid/issues/100#issuecomment-20553864

Do you realize that we are dealing here with basic Ruby and Rails knowledge, and not some intricacy of the WiceGrid plugin?

Please use GitHub Flavored Markdown to display your code correctly, so far I've been editing your comments to make them readable.

**Comment by leikind** [comment]
one more thing. If `user.roles` returns an empty array, this is still a true value. `if user.roles` is always true
