### ISSUE TITLE
Nested Attributes

### ISSUE THREAD

**Issue by motapuma** [leikind/wice_grid#101]
I have the  models

Purchase Requisition
{
has_many :requisition_entries
belongs_to :creator
}
Requisition Entries{
belongs_to :purchase_requisition
}
Creator{
 name:string
}

I want to display in a grid the Requisition Entries....but i am able to display the "creator.name"... BUT  i am not able to have a column that sort the creators by the "name" property!

**Comment by leikind** [comment]
Please show you view code and `initialize_grid` in the controller.

Please use  GitHub Flavored Markdown to render code nicely

**Comment by leikind** [comment]
I cannot do anything without the code. Please post your code

**Comment by leikind** [comment]
No code - no solution
