### ISSUE TITLE
Add dynamic color from database model to a specific column

### ISSUE THREAD

**Issue by mostafahussein** [leikind/wice_grid#104]
Well , in my show.html.erb i made a dynamic color to a specific tag in the view. in the index.html.erb , i am using wice_grid , how could i add a dynamic color to a specific column ??

**Comment by leikind** [comment]
Your column block can return a 2-item array where the first item is the html as usual, and the second is an array of HTML attibutes for the `td` tag.

Look here http://wicegrid.herokuapp.com/styling in `_grid2.html`

**Comment by mostafahussein** [comment]
`g.column name: 'Current State', attribute: 'name', model: 'State', auto_reload: true do |ticket|
                if ticket.state
                  ticket.state.name
                  css_class = ticket.state
                else
                  Not defined yet
                end
              end`

this column is return 'Emergency' or 'High' or 'Normal' , and in States model i have a color attribute, and background attribute which should provide css according to the state. can that be possible using wice_grid ?

**Comment by leikind** [comment]
I've already given you a response to this question. Yes, this is possible. Please read attentively my previous post and follow the link.

**Comment by mostafahussein** [comment]
the yellow color only is working the other two colors is not appearing what is the problem here ?

```
            g.column name: 'Current State', attribute: 'name', model: 'State', auto_reload: true do |ticket|
                if ticket.state
                  if ticket.state.name == 'Emergency'
                    [ticket.state.name, {style: 'background-color:  rgb(255, 0, 0)'}]
                  end
                  if ticket.state.name == 'High'
                    [ticket.state.name, {style: 'background-color:  rgb(255, 165, 0)'}]
                  end
                  if ticket.state.name == 'Normal'
                    [ticket.state.name, {style: 'background-color:  rgb(255, 255, 0)'}]
                  end
                else
                  Not defined yet
                end
              end
```

**Comment by leikind** [comment]
The problem is that the value of the block is always the last expression, and your last expression is the last `if` block which returns either a 2 item array or nil. 

Use `if elsif elsif end` or `case when when end`

**Comment by mostafahussein** [comment]
Thanks !
