### ISSUE TITLE
Bootstrap 3 - pagination class goes on the UL tag not the DIV

### ISSUE THREAD

**Issue by asgeo1** [leikind/wice_grid#106]
In bootstrap 3, the `pagination` CSS class goes on the `<ul>` tag, not the `<div>` tag.

They also have different sizes of pagination. So you can use "small" or "large" versions in addition to the default size.

```
<ul class="pagination pagination-lg">...</ul>
<ul class="pagination">...</ul>
<ul class="pagination pagination-sm">...</ul>
```

I worked out I could override the _paginator.html.erb partial to set it how I liked, but thought I would raise the issue anyway.

Maybe in the interim you could have a setting so it switches between bootstrap 2 or 3 mode?

**Comment by leikind** [comment]
Right. WiceGrid is only compatible with Bootstrap 2, didn't try it with Bootstrap 3. A setting is a possible solution.

**Comment by leikind** [comment]
@asgeo1 How do you use Bootstrap 3 with Rails? https://github.com/thomas-mcdonald/bootstrap-sass seems to be on Bootstrap 2

**Comment by asgeo1** [comment]
@leikind, I'm using anjlab/bootstrap-rails

**Comment by leikind** [comment]
Please try version 3.4.1, it should work well with both Bootstrap 2 and Bootstrap 3.

**Comment by francistm** [comment]
@leikind How does "~> 3.4.0" support Rails 3? Thanks.

**Comment by leikind** [comment]
@francistm 3.\* versions work with Rails 3.

**Comment by disyukvitaliy** [comment]
Do you still using version 2? I have some trouble with duplication of pagination class. Bootstrap margin is used twice for both elements (div.pagination, ul.pagination). I use Bootstrap 3.
Hope you understand my english :)

**Comment by leikind** [comment]
Well, we can do this in your language then :)

Версию 2 ужe давно-давно  не использую, и нет даже приложения на rails 2 c wicegrid, которое я бы поддерживал сейчас.

**Comment by disyukvitaliy** [comment]
Thank for quick answer. But :)

What version do you mean? Bootstrap 2 or rails 2?
I mean what Kaminari have template with the next markup
https://github.com/amatsuda/kaminari/blob/master/app/views/kaminari/_paginator.html.haml
%nav.pagination – just one  pagination class per template
Your template have the couple of tags with pagination class. One for div and second for ul. https://github.com/leikind/wice_grid/blob/rails3/app/views/kaminari/wice_grid/_paginator.html.erb
It leads to increase margin in 2 times (.pagination{margin: 21px 0;})
I can't understand why we need div.pagination. I think ul.pagination is enough

And I have one more question about filters :)
https://github.com/leikind/wice_grid/blob/rails3/lib/wice/columns/column_integer.rb 12th line. You added input-sm class
https://github.com/leikind/wice_grid/blob/rails3/lib/wice/columns/column_custom_dropdown.rb 25th line. I don't see it
Filter controls have a different size
I can change it only via overriding entire class. Maybe I missed something?

**Comment by leikind** [comment]
Sorry, I misunderstood you question. No, the plugin doesn't use Bootstrap 2 any more. If you feel some markup is wrong, please make a pull request and I will merge
