### ISSUE TITLE
Filter is not working -- which is the consequence of unable to load javascript files.

### ISSUE THREAD

**Issue by c-jiezho** [leikind/wice_grid#107]
I can sort the columns, but all the functionalities of filter are not working. For example, if set "show_filters: :when_filtered", click show filter icon, the row contains the filters will not show up. If I set the show_filters: :always, and type in anything in any filter text box, and click filter icon, the page won't load. What's the cause? I suspect it is related to jquery, but don't know how to fix it. Can anyone help?

**Comment by leikind** [comment]
Please take a look is there are JS errors in  your JS console.
Also, please provide the version of the framework

**Comment by c-jiezho** [comment]
The framework is
gem 'rails', '3.2.11'

When I inspect the Error console, I got the following message:
[10:34:44.020] The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.

I followed all the instruction and there is a line //= require wice_grid.js in application.js. Since it’s not working, so I copy the file directly in the same directory.

**Comment by leikind** [comment]
This is weird. And this is not WiceGrid which does it. Could you try to turn off the rest of javascript on the page and see if this message persists? 

Which browser is it?

**Comment by c-jiezho** [comment]
firefox 9.0.1.
Let me try take off the rest of javascripts.
Thanks.

**Comment by leikind** [comment]
Another thing you could do it try to find `<script src="/wice_grid.js" type="text/javascript"></script>` in the source of the page. If it is present, try to type `WiceGridProcessor` in the JS console and say what the result of this expression is

**Comment by c-jiezho** [comment]
After I write 
<%= javascript_include_tag 'wice_grid' %>
The popup alert are gone. 

## This is the response in JS Console.

[11:20:24.157] WiceGridProcessor
[11:20:24.173] function WiceGridProcessor(name, baseRequestForFilter, baseLinkForShowAllRecords, linkForExport, parameterNameForQueryLoading, parameterNameForFocus, environment) {this.name = name;this.baseRequestForFilter = baseRequestForFilter;this.baseLinkForShowAllRecords = baseLinkForShowAllRecords;this.linkForExport = linkForExport;this.parameterNameForQueryLoading = parameterNameForQueryLoading;this.parameterNameForFocus = parameterNameForFocus;this.environment = environment;this.filterDeclarations = new Array;this.checkIfJsFrameworkIsLoaded();}

It seems the file and WiceGridProcessor object has been referenced. But the filter is still not working. Thanks for the hint, we have some progress. :+1:

**Comment by c-jiezho** [comment]
I got  [11:29:39.200] jQuery is not defined @ http://0.0.0.0:3000/assets/wice_grid_init.js?body=1:4 after I flush the page.

**Comment by leikind** [comment]
I don't get it

there was no `<script src="/wice_grid.js" type="text/javascript"></script>` on page?

**Comment by c-jiezho** [comment]
wice_grid.js is located in app/assets/javascripts/ which I copied directly into the same directory as application.js.
I tried <script src="/wice_grid.js" type="text/javascript"></script> but the alert still popup.
so i tried <%= javascript_include_tag 'wice_grid' %>, the asset pipeline of ROR find the resource.

**Comment by leikind** [comment]
there's something very-very wrong with what you are doing. `//= require wice_grid` should include the necessary javascript without any copying.

**Comment by c-jiezho** [comment]
The Filter finally works. Thank you so much.

**Comment by c-jiezho** [comment]
You are right. I used the strange way to make the the filter works.
I will try the formal way.

**Comment by leikind** [comment]
It's not just filters not working... It's correctly loaded javascript files.

The sorting links are just links, they do not require any javascript

**Comment by c-jiezho** [comment]
For someone with the same issue, remember to reference jquery before wice_grid.js, since the wice_grid plugin refer jquery internally. I will post the formal way result after I try. Thanks to the creator of WiceGrid.

**Comment by leikind** [comment]
jQuery is mentioned in the Requirements section https://github.com/leikind/wice_grid#requirements  :)
