### ISSUE TITLE
Date filter helper style :inputs

### ISSUE THREAD

**Issue by patie** [leikind/wice_grid#111]
Hi, 

can you extend date filter helper style ?

I have this proposition:

two text inputs (from/to) and programmer have option to map javascript to theses inputs (for example any jquer date picker plugin etc.)

what do you think ?

**Comment by leikind** [comment]
filters are made as standalone as possible. Take a look https://github.com/leikind/wice_grid/tree/rails3/lib/wice/columns and https://github.com/leikind/wice_grid/blob/rails3/lib/wice/columns/column_processor_index.rb

It should be possible to write your own filter the way you prefer

**Comment by patie** [comment]
you can explain you answer please ? how can i write (and set) filter for some column please

**Comment by leikind** [comment]
I am saying that I have made it possible to write your own filters relatively easy

**Comment by patie** [comment]
hehe yeah im understood what you say - i mean if you can show how can i write own filter, im newcomer (basic example)

**Comment by leikind** [comment]
I am sorry, i can't, I am afraid you are on your own here. The existing filters _are_ the examples. https://github.com/leikind/wice_grid/tree/rails3/lib/wice/columns
