### ISSUE TITLE
Can wice_grid retrieve data from view vs physical table directly?

### ISSUE THREAD

**Issue by c-jiezho** [leikind/wice_grid#112]
I create a view based on a physical table.
In that view I convert unix timestamp in physical table to datetime by `from_unixtime(xxx.time_stamp)`, the time format shows correctly such as 2013-01-29 07:52:54 in the view, but when I use
`g.column :name => 'Access_time', :attribute => 'access_time'`
there are trailing "UTC" append to the time 2013-01-29 07:52:54 UTC. 

This is just trivial issue.

Another major one is I wrote a mysql function such as 

``` sql
CREATE DEFINER=`root`@`localhost` FUNCTION  `apachelogs`.`source_country_code`(virtual_host varchar(255)) RETURNS varchar(10) CHARSET latin1
BEGIN
  declare scc VARCHAR(10);
  IF virtual_host REGEXP 'aprdc1' THEN 
     SET scc = "SG" ;
  ELSEIF virtual_host REGEXP 'hyd' THEN
     SET scc = "IN" ;
  ELSEIF virtual_host REGEXP 'eu' THEN
     SET scc = "EU" ;
  ELSEIF virtual_host REGEXP 'cn' THEN
     SET scc = "CN" ;
  ELSE
     SET scc = "US";
  END IF;

  RETURN scc;
END
```

I used that function create a new column in the view based on the existing column
by CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW  `apachelogs`.`timestamp2datetime_logs` AS select  `source_country_code`(`git_log`.`virtual_host`) AS `source_country_code` from `git_log`, the new column are populated with data.
but again when I use
g.column :name => 'Source Country Code', :attribute => 'source_country_code'

no data for that column shows on the browser, all field for that column are blank?

Do these issues caused by using view instead of table?

**Comment by c-jiezho** [comment]
I figured out the no data for shows for the column on the browser by myself.
It seems like column name in view matters. I change the "source_country_code" to "source_cc" for that column in view. I also change the function name from lowercase 'source_country_code' to uppercase 'SOURCE_COUNTRY_CODE'.

**Comment by leikind** [comment]
As to your first question, you can format any data in a block the way you want:

```
g.column :name => 'Access_time', :attribute => 'access_time' do |ar_instance|
   format_it_the_way_you_like(ar_instance.your_field)
end
```

As for the second question: WiceGrid just builds a query via ActiveRecord. You can try  reading your view with ActiveRecord, if you can do it, WiceGrid can do it as well.
