### ISSUE TITLE
table with two models and not repeated attribute

### ISSUE THREAD

**Issue by mostafahussein** [leikind/wice_grid#113]
```
Supervisors | Advisors | Student Class |
 Sprvisor1   |  Foobar1 |   Class A        |
                  |  Foobar2 |   Class B        |
                  |  Foobar3 |   Class C        |
                  |  Foobar4 |   Class D        |
```

how to create a table like this ? what theory should be followed ? i have two models i need to have both of them in one table and the most important thing is to have one supervisor name ( not repeated ) because in my models each supervisor has number of advisors belongs to him, or in a more clear example like when you say each country has many states , and we need to make the name of country not repeated

**Comment by leikind** [comment]
How is this question related to WiceGrid?

**Comment by mostafahussein** [comment]
Does wicegrid support making this or not ? mirging many blank cells in one cell

**Comment by mostafahussein** [comment]
Like this http://help.adobe.com/en_US/livecycle/9.0/designerHelp/images/grouped_table.gif

**Comment by leikind** [comment]
No
