### ISSUE TITLE
saved queries with rails 4

### ISSUE THREAD

**Issue by francescob** [leikind/wice_grid#114]
there's an error when using the routes helper Wice::define_routes(map, 'queries'):

undefined local variable or method `map' for #ActionDispatch::Routing::Mapper:0x007fd262f65310

i've solved it by manually adding these routes:

post '/wice_grid_serialized_queries/:grid_name',
          :to => "queries#create",
          :as => 'create_serialized_query'

  post '/wice_grid_serialized_queries/:grid_name/:id',
          :to => "queries#delete",
          :as => 'delete_serialized_query'

**Comment by bhushangahire** [comment]
You can pass self instead of map. Its routes object.

**Comment by leikind** [comment]
documentation fixed
