### ISSUE TITLE
:Group

### ISSUE THREAD

**Issue by Seaborg** [leikind/wice_grid#117]
Hi,

I can't figure out how to use :group option in wice_grid

All I need is to group by patient id and within the group order by :date column:
@clinical_visits = initialize_grid(ClinicalVisit,
      :joins => [:subject],
      :include => [:subject],
      :group => ['subjects.subjectid'],
      :name => 'g1',
      :order => 'clinical_visits.date',
      :order_direction => 'asc',
      :csv_file_name => 'clinical_visits' )

This does not work, i don't even see sql Group in my logs. I've tried all sorts of options
with no result. I'm using  wice_grid (3.3.1) and I love it, please help.

**Comment by Seaborg** [comment]
Ok,
 So I managed to bypass the problem with :custom_order
      :order => 'clinical_visits.id',
      :custom_order => {
        'clinical_visits.id' => 'subjects.subjectid, clinical_visits.date'
      },

but it would be nice to have a group option for future, perhaps an example at:
wicegrid.herokuapp.com

**Comment by leikind** [comment]
I am sorry for such a late response. Eventually did the code do what you needed?

**Comment by Seaborg** [comment]
yep

**Comment by leikind** [comment]
If you still have access to that code, would you please post here the call to `initialize_grid` and the grid definition in the view? I'd be very grateful.

**Comment by Seaborg** [comment]
``` ruby
@clinical_visits = initialize_grid(ClinicalVisit,
      :joins => [:subject],
      :include => [:subject],
      # :group => ['subjects.subjectid'],
      :name => 'g1',
      :order => 'clinical_visits.id',
      :custom_order => {
        'clinical_visits.guid' => 'subjects.subjectid, clinical_visits.date'
      },
      :order_direction => 'asc' )

```

**Comment by leikind** [comment]
I assume that line 

``` ruby
# :group => ['subjects.subjectid'],
```

is actually uncommented
