### ISSUE TITLE
Dropdown Filters dont send the request when selecting a value

### ISSUE THREAD

**Issue by golddiga** [leikind/wice_grid#118]
Hi, I' ve setup a very basic wice-grid and try to get the boolean filter to work. somehow it doesnt send the request when selecting yes / no ... just when i go to any other field and hit enter the filter gets applied... 

I dont get any errors in the console. Is there any Javascript event I can put manually to get this working?

many thanks

**Comment by leikind** [comment]
more info needed: code, version, etc

**Comment by tombroomfield** [comment]
Sorry to pull up such an old issue, but I am having the same issue.

``` ruby
  g.column name: 'Type', attribute: 'type', custom_filter: :auto do |field|
    field.type.titleize
  end
```

When I select the dropdown, nothing happens.
I am on the latest version, 3.4.12

**Comment by tombroomfield** [comment]
It works successfully if I set the dropdown and then move to a text filter and tap enter, this is not ideal though.
