### ISSUE TITLE
Custom SQL queries

### ISSUE THREAD

**Issue by aldesantis** [leikind/wice_grid#119]
First of all, my congratulations for this awesome gem. WiceGrid is exactly what I need in my project!

Now let's come to my feature request: in a certain grid I have a "status" column whose value I calculate AFTER retrieving the record. However, it's still possible to filter the records with a custom SQL query (in my case it's just a matter of comparing two dates).

It would be nice if I could write something like:

``` ruby
g.column 'Foo', filter: 'foo > :query'
```

You could also allow to use a Proc:

``` ruby
g.column 'Foo', filter: proc{ |q| where('foo > :query', query: q) }
```

There are other cases where this would be useful: for example, I have a `Customer` model with separate columns for the customers' first and last names. I want to display the full name in the grid, but still allow my users to filter the records:

``` ruby
column 'Full name', filter: proc{ |q| where("CONCAT(first_name, last_name) LIKE :query", query: "%#{q}%") } do |customer|
  "#{customer.first_name} #{customer.last_name}"
end
```

I'm not really sure whether this is something achievable or not, let me know!

Thanks for your time.

**Comment by leikind** [comment]
Sorry for the late response.

I m not sure I fully understand this.

You say

> in a certain grid I have a "status" column whose value I calculate AFTER retrieving the record.

What do you mean by "calculate". Another sql query?

Anyway, it is not doable right now and I personally find this API too  complex.

As for the second case I used to create column `name` which is populated by a `before_save` method concatenating first_name and second_name

**Comment by aldesantis** [comment]
Yes, eventually we've decided to cache the calculated value in a column, also to avoid stressing the database too much.

Thank you anyway.

**Comment by fabdbt** [comment]
Hi,

I would like to know if wice_grid integrated this behaviour into the gem ?
I'm actually looking for a way to find phone numbers through filter and I would like to use a REGEXP SQL request instead of the basic LIKE one and the solution of @alessandro1997 looks like what I was looking for.

Is there a solution ?
Thank you.

**Comment by leikind** [comment]
This functionality is not present in the gem. The docs explain the API and do not hide anything
