### ISSUE TITLE
polymorphic associations

### ISSUE THREAD

**Issue by cpzhao** [leikind/wice_grid#12]
Great grid!  I really like it.

I have one problem.  I can't figure out how to get a polymorphic relationship working, as I have to specify the class name explicitly for any joins.

Could you help?  Thanks,

**Comment by cpzhao** [comment]
sorry, I figured it out.  Works great now.

**Comment by leikind** [comment]
Great

**Comment by robertleib** [comment]
Is there any documentation on how to get a polymorphic relationship working?

**Comment by leikind** [comment]
Use :include => :your_association in initialize_grid(), just like you would do using vanilla ActiveRecord. If this is not the answer to your question, please be more specific about what you want to do.

**Comment by shubhamkhanna** [comment]
how to deals with "through relationship" in wice grid?

**Comment by leikind** [comment]
1) Use `:include => :your_association` in `initialize_grid()`, just like you would do using vanilla ActiveRecord.
2) In the grid helper use `:model => ''NameOfYourModelClass"`
