### ISSUE TITLE
DATEPICKER_YEAR_RANGE constant format

### ISSUE THREAD

**Issue by freemanoid** [leikind/wice_grid#121]
There is no mention in readme about `DATEPICKER_YEAR_RANGE` constant format. 
I've learned by experimentation that the correct format is 

``` ruby
Wice::Defaults::DATEPICKER_YEAR_RANGE = "2010:#{Date.today.year}"
```

Is it correct? Why there is no information in readme about it?

**Comment by leikind** [comment]
This is a TO DO for me. Thank for the remark

**Comment by leikind** [comment]
I am wrong, there is information about this constant in the README. Closing

**Comment by freemanoid** [comment]
> I am wrong, there is information about this constant in the README. Closing

There is information about the constant but there is no information about the format of its value. That was the note.

**Comment by leikind** [comment]
This is not a format. This is Ruby.

What is not clear here: https://github.com/leikind/wice_grid/blob/rails3/lib/generators/wice_grid/templates/wice_grid_config.rb#L145

**Comment by freemanoid** [comment]
All is clear after looking at the sources, just wanted to explicitly notice about that in README.
I mean that `"2000:2042"` is not intuitive. There is information that it can be changed in javascript but nothing about the constant.
