### ISSUE TITLE
Compatibility with Globalize3

### ISSUE THREAD

**Issue by restogeek** [leikind/wice_grid#123]
I am trying to use wice_grid together with Globalize3.

How should I define the join tables and related attributes?

Here is my DB schema, for a Supplier Model. I want to have the translated name inside my wice_grid.

``` ruby
  create_table "supplier_translations", force: true do |t|
    t.integer  "supplier_id", null: false
    t.string   "locale",      null: false
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
  end

  add_index "supplier_translations", ["locale"], name: "index_supplier_translations_on_locale", using: :btree
  add_index "supplier_translations", ["supplier_id"], name: "index_supplier_translations_on_supplier_id", using: :btree

  create_table "suppliers", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end
```

Thanks a lot for any help!

Thierry

**Comment by restogeek** [comment]
In order to have ordering available for the name, I need to define the attribute:

``` haml
- g.column  name: 'Name' do |supplier|
  - supplier.name
```

However, then, I get the error message:

```
WiceGrid: Column 'name' is not found in table 'suppliers'! If 'name' belongs to another table you should declare it in :include or :join when initialising the grid, and specify :model in column declaration.
```

So, I try to define the grid as:

``` ruby
@suppliers_grid = initialize_grid(
  Supplier,
  joins: [:supplier_translations]
)
```

But, I still get the same error message.

Thierry

**Comment by restogeek** [comment]
Further information about compatibility issues with Globalize.

The following: It is also possible to use an ActiveRecord::Relation instance as the first argument:

``` ruby
@tasks_grid = initialize_grid(Task.where(:active => true))
```

Does not work with Globalize.

You will get the error message whe using the grid in your view:

```
undefined method `per' for #<Globalize::ActiveRecord::Relation::Globalize_ActiveRecord_Relation_Task:0x0000000c4fd178>
```

Let me know if you need further information to improve Wice Grid. 

Awesome gem by the way! :-)

**Comment by restogeek** [comment]
UPDATE: The following report is WRONG. It is not related to Globalize

I remove Globalize from my project for the time being and get the same error.

``` ruby
@grid = initialize_grid(
  Product.all
)
```

Error message:

```
undefined method `per' for #<ActiveRecord::Relation::ActiveRecord_Relation_Product:0x0000000a62cd70>
```

So, it seems related to... maybe... will_paginate? I am using will_paginate-3.0.5 and wice_grid-3.4.2 with rails-4.0.0

Ref: https://github.com/leikind/wice_grid/issues/77

**Comment by vmloliveira** [comment]
Hi there,

Any workaround for this issue ? I'm facing the same problem...

Like beermania wrote "fantastic gem" :)

Cheers,
Vítor

**Comment by jpmermoz** [comment]
Hi, I'm having the same issue. Wice grid can't find the translated attributes.
Thanks!

**Comment by leikind** [comment]
@beermania 
Since 3.2.pre2 WiceGrid is not compatible with will_paginate because internally it uses kaminari for pagination, and kaminari is not compatible with will_paginate!

It's in the docs

**Comment by leikind** [comment]
@jpmermoz WiceGrid does not and should not "find translated attributes." Also, seems like your problem is different from the one in this ticket. Open a new one, paste your code, versions, stacktraces, etc

**Comment by vmloliveira** [comment]
Hi all,

I know this topic is closed, but I have a trick to bypass the issue of translated columns using wice "fantastic" grid :)

Model

class Product < ActiveRecord::Base
  #translated attribute
  translates :description
end

Controller [index action]
...
def index
    #.with_translations is mandatory to force the join
    @products_grid = initialize_grid(Product.with_translations('en'))
end
...

View
...
g.column name: 'Description', attribute: 'description', model: 'Product::Translation' do |product|
    product.description
  end
...

Globalize creates a model at runtime formatted in the following way: "[YourModel]::Translation".

Both order and filter works this way ;)

I hope this helps.

Cheers,
Vítor
