### ISSUE TITLE
column settings get ignored depending on sort order

### ISSUE THREAD

**Issue by dsandber** [leikind/wice_grid#127]
This is a VERY SERIOUS bug.  I made a column such as:

g.column name:'Foo', attribute:'foo' do |r|
  'Dog food'
end

Depending on the whether the column is sorted ascending or descending either 'Dog food' is shown or the underlying foo attribute is shown!  I tried debugging it for a while but couldn't figure out what was causing this.

**Comment by leikind** [comment]
Please post the initialize_grid declaration and the grid declaration together with the version of the framework, environment, and the deployment stack details. Screenshots are also welcome

**Comment by dsandber** [comment]
Sorry, I don't remember what this was about any more! :)  Guess you can close it and see if it comes up again.

**Comment by leikind** [comment]
sorry for such a late response
