### ISSUE TITLE
Group actions

### ISSUE THREAD

**Issue by slayer** [leikind/wice_grid#13]
Hi

Did you think about group actions? One column with checkboxes and buttons like: "Delete selected", "Mark as read", etc

Thanks

**Comment by leikind** [comment]
Yes, I did think about it. 
Could you suggest an API that you would use?

**Comment by slayer** [comment]
controller code like http://gist.github.com/257883

**Comment by slayer** [comment]
and view (HAML) like http://gist.github.com/257883

**Comment by leikind** [comment]
See this commit (in the experimental branch): http://github.com/leikind/wice_grid/commit/c15a0247caf2e019d4b2c205b184086e9672771b
