### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by henrydjacob** [leikind/wice_grid#130]
Getting 'Cannot read file' exception while exporting CSV file
fails at export_grid_if_requested

**Comment by leikind** [comment]
Please post the `initialize_grid` declaration  and the grid declaration together with the version of the framework, environment, and the deployment stack details

**Comment by henrydjacob** [comment]
```
@students_grid = initialize_grid(@students, 
  :name => 'g1',
  :order => 'students.name',
  :order_direction => 'desc',
  :include => [:guardian, :user, :academic_admissions => [:course]],
  :enable_export_to_csv => true,
  :csv_field_separator => ';',
  :csv_file_name => 'students')

export_grid_if_requested('g1' => 'students_grid')
```

fails at line export_grid_if_requested and display 

Cannot read file &#47;var&#47;folders&#47;4l&#47;9qq5s89x6gbb3mn3mqlmyxlw0000gn&#47;T&#47;g120140329-5322-qadxnk

**Comment by leikind** [comment]
What is the version of the framework, environment, and the deployment stack details?

**Comment by henrydjacob** [comment]
Thanks leikind, I managed to solve this, the issue is related to the template. I was using Slim template, therefore my grid is named as "_students_grid.html.slim". it started working once I converted to erb.
