### ISSUE TITLE
Attribute: 'name' make wice_grid filter js not work in Rails 4.0+

### ISSUE THREAD

**Issue by kiat-mao** [leikind/wice_grid#132]
In my project,I find the filter did not work and with error message：
 [23:19:12.624] TypeError: filterDeclaration is null @ http://localhost:3000/assets/wice_grid_init.js?body=1:19

I tried many way to resolve the problem.At last, I found that the error is because of a column with  " attribute: 'name' " and  everythin is ok when I changed the column name

I think this is maybe a bug :)

Thank you for your replay

**Comment by leikind** [comment]
Please post your grid declaration.
