### ISSUE TITLE
Dynamic columns

### ISSUE THREAD

**Issue by gfaraj** [leikind/wice_grid#135]
Is there a way to automatically have dynamic columns or is this something I would have to do manually?

Say I have a table [fee] that contains a fee that applies to all users and [user_fee] that has a user, fee, and amount paid, and I want to see a list of users, and how much they owe of each fee.

I want a grid like this:

Name     Fee-1    Fee-2 ... Fee-N  Total
...
Total     

Is this easily done with Wice?

**Comment by leikind** [comment]
you can have any ruby code inside the main grid block:

```
<%= grid(@tasks_grid) do |g|

  if something
    g.column do |task|
     ...
    end
 end
end -%>
```

or you might have a loop.
