### ISSUE TITLE
Totals row

### ISSUE THREAD

**Issue by gfaraj** [leikind/wice_grid#138]
I would like to add a row at the end that shows a total for one or more columns. Is that possible?

**Comment by leikind** [comment]
```
g.last_row do |rec|
  # return your html as a string
end
```

https://github.com/leikind/wice_grid/blob/rails3/lib/wice/grid_renderer.rb#L419

**Comment by gfaraj** [comment]
Was wondering if there was something that did it automatically, but that works. Thanks!

**Comment by gfaraj** [comment]
Wait... how would I retrieve the values to sum for a total?

**Comment by leikind** [comment]
how about using a variable in the block?

**Comment by leikind** [comment]
something like this

```
<% sum = 0%>
<% grid() do |g|

  g.column do |rec|
    sum += rec.something

    rec.whatever
  end

  g.last_row do |rec|
    '<tr><td>' + sum.to_s + '</td></tr>'
   end
end %>
```

**Comment by gfaraj** [comment]
Oh, yeah that's a good idea. Thanks.
