### ISSUE TITLE
undefined method `capable_of_hosting_filter_related_icons?' for nil:NilClass

### ISSUE THREAD

**Issue by yeyong123** [leikind/wice_grid#139]
```
#controller
def index
@products_grid = initialize_grid(Product, order: 'products.name', per_page: 10)
end

#View
                 <%= grid(@products_grid) do |g| %>
11:         g.column name: 'title',attribute: 'title' do |poroduct|
12:         link_to(product.name,product_path(product))
13:     <% end %>

app/views/products/index.html.erb:10:in `_app_views_products_index_html_erb__4477419195876775173_69838317139400'
```

**Comment by leikind** [comment]
Your view code does not seem to be valid ERB. Can please be precise and copy paste the valid code?

Also please submit the version of the plugin and the framework

**Comment by yeyong123** [comment]
thank you , I see code is wrong,Code is wrapped in <%= %>,but I do not!

2014-03-05 18:32 GMT+08:00 Yuri Leikind notifications@github.com:

**Comment by leikind** [comment]
Please post the complete correct code ,  the version of the plugin and the framework, so that I can help you

**Comment by yeyong123** [comment]
thanks ,
