### ISSUE TITLE
No upgrade strategy exists

### ISSUE THREAD

**Issue by mikhailian** [leikind/wice_grid#14]
Running
  script/plugin install git://github.com/leikind/wice_grid.git
  script/generate wice_grid_assets
in a setup having already wice_grid configured leads to unpredictable results.

A upgrade strategy from previous versions of wice_grid could be helpful. In the meantime, copying wice_grid_assets by hand helps.

**Comment by leikind** [comment]
Can you be more precise, what unpredictable results are we talking about

**Comment by mikhailian** [comment]
For instance, a stacktrace showing that Wice::Defaults::POPUP_PLACEMENT_STRATEGY is not declared.

As a minimal solution, you should update the documentation, outlining an upgrade path from previous versions.

**Comment by leikind** [comment]
script/generate wice_grid_assets   is supposed to overwrite config/initializers/wice_grid_config.rb

If you allow this, no problem will arise, otherwise you should know what you are doing (сам себе злой буратино). You should allow the script to install the new config and then re-apply your changes. Frankly I don't see the problem at all.

**Comment by mikhailian** [comment]
I did not overwrite in my case nor  did it ask to overwrite.

P.S. Mind that I use jruby.

**Comment by leikind** [comment]
Here's is what my documentation says:

"To copy the plugin initializer, icons, javascripts, and stylesheets to correct location, run the following command:

   ./script/generate wice_grid_assets
Using ./script/generate to copy assets gives the advantage of collision control - if a file with the same name already exists at the given location, the script will pause and ask the user about what action to take."

Please enlighten me what else is not clear? There is a config file, and there is a method to copy all the assets to the proper locations. You do not run the generator script or you run the generator and refuse to overwrite the config, and you expect the plugin to work? Are you kidding me? Can't you just diff you config/initialializers/wice_grid.rb 
with vendor/plugins/generators/wice_grid_assets/templates/initializers/wice_grid_config.rb before the upgrade, thus figuring out what changes you applied in the past, then install the latest config with the generator script, and then re-apply your changes?

This is called programmer's work.

**Comment by mikhailian** [comment]
As I said, when upgrading wice_grid from the version that dated ~ Oct, 21, script/generate wice_grid_assets did not produce any output and silently completed.

Unfortunately, I did not keep the old environment — can not redo the clean test.

**Comment by leikind** [comment]
In my opinion the problem is non-existant.
