### ISSUE TITLE
will_paginate gem is not detected by wice_grid, only works when installed as a plugin

### ISSUE THREAD

**Issue by mikhailian** [leikind/wice_grid#15]
If will_paginate is installed as a gem, e.g. with 

  jruby -S gem install mislav-will_paginate

the following stacktrace occurs:

$ RAILS_ENV=development jruby script/server 
=> Booting WEBrick
=> Rails 2.3.3 application starting on http://0.0.0.0:3000
/home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:443:in `load_missing_constant': uninitialized constant WillPaginate (NameError)
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:80:in`const_missing_with_dependencies'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:92:in `const_missing'
        from /home/lowry/hobby/buh/vendor/plugins/wice_grid/lib/grid_renderer.rb:9
        from /home/lowry/hobby/buh/vendor/plugins/wice_grid/lib/grid_renderer.rb:31:in`require'
        from /home/lowry/lib/jruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in`require'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:521:in `new_constants_in'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in`require'
        from /home/lowry/hobby/buh/vendor/plugins/wice_grid/lib/wice_grid.rb:4
        from /home/lowry/hobby/buh/vendor/plugins/wice_grid/lib/wice_grid.rb:31:in `require'
        from /home/lowry/lib/jruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:521:in`new_constants_in'
        from /home/lowry/lib/jruby-1.3.1/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:156:in `require'
        from /home/lowry/hobby/buh/vendor/plugins/wice_grid/init.rb:1:in`evaluate_init_rb'

The usual 

  config.gem "will_paginate", :version => '2.3'

within the Rails::Initializer.run does not work.

**Comment by leikind** [comment]
This commit should fix the issue: http://github.com/leikind/wice_grid/commit/244eea2cdba71a88fdb3ae6a58a06d9721ff2c89
