### ISSUE TITLE
Issue with order

### ISSUE THREAD

**Issue by afdev82** [leikind/wice_grid#154]
When I try to order a field of my Configurations::Configuration model, I get the following error:

<pre>
PG::UndefinedColumn: ERROR:  column configurations.configurations does not exist
LINE 1: ... FROM "configurations"."configurations"  ORDER BY "configura...
                                                             ^
: SELECT  "configurations"."configurations".* FROM "configurations"."configurations"  ORDER BY "configurations"."configurations" asc LIMIT 20 OFFSET 0
</pre>

I initialized the grid simply in this way: 

``` ruby
@configurations = initialize_grid(Configurations::Configuration)
```

In my view I have:

``` ruby
grid(@configurations, allow_showing_all_records:  false) do |g|
  g.column name: 'Project ID',
           attribute: 'configuration_id' do |configuration|
    configuration.configuration_id
  end
  g.column name: 'Project name',
           attribute: 'name' do |configuration|
    configuration.name
  end
end
```

Thank you in advance!

**Comment by afdev82** [comment]
The query string is:

<pre>grid[order]=configuration_id&grid[order_direction]=asc</pre>

If I submit this:

<pre>grid[order]=configurations.configuration_id&grid[order_direction]=asc, it works</pre>

**Comment by leikind** [comment]
Please give more info about your data model

**Comment by afdev82** [comment]
I have the "Configurations::Configuration" class, that represents a "configuration" of one product in a "configurator" web application.
This is the class without its methods:  

``` ruby
class Configurations::Configuration < ActiveRecord::Base
  include GettersHelper
  include JsHelper

  self.primary_key = 'configuration_id'
  self.table_name  = 'configurations.configurations'

  serialize :included, JSON
  serialize :restricted, JSON

  <private code>

```

**Comment by leikind** [comment]
WiceGrid is likely not to work correctly with posgresql tables in non-public schemas, i.e. with table names like  'configurations.configurations'. Cannot say for sure because I don't use Postgresql, and all users of WiceGrid with posgresql use the public schema, a flat list of tables.

**Comment by afdev82** [comment]
Ok, thanks!  
Do you think is it possible to make a wrapper or initializer to change the behaviour of WiceGrid to handle this?

**Comment by leikind** [comment]
I am pretty sure it would be not that difficult to solve this problem, unfortunately at present I cannot say when I'll do it. But I will accept pull requests :-)

**Comment by afdev82** [comment]
Ok, thanks.
I will think about it, if I can I would be proud to contribute ;)

**Comment by brian-vogogo** [comment]
The issue is `quote_table_name("public.car.color")` returns `"public"."car"` and drops the `.color`.

We have the same issue while using the Apartment gem to switch between public schemas.

**Comment by afdev82** [comment]
Thank you @brian-vogogo ;)
