### ISSUE TITLE
Custom html arguments for filters

### ISSUE THREAD

**Issue by kabturek** [leikind/wice_grid#156]
Hi
i have a detached custom filter and im outputing it with 

``` haml
= grid_filter @companies_grid, :esendex_account_filter
```

is it possible to add params to the select ? (the one with `.custom-dropdown` class) i would like to add class 'form-control' to add default bootstrap styles without adding all the styles to `.custom-dropdown`.

i was thinking along somthing like `:filter_html` for the column definition, or a 3rd param for grid_filter. 

The other use case it would be usefull is for example to adding placeholders for html text inputs in filters.

**Comment by leikind** [comment]
Unfortunately the API does not allow for this. I can only suggest a dirty fix to add css classes via jquery.

**Comment by kabturek** [comment]
ok thx. would it be a good feature for a PR ?

**Comment by leikind** [comment]
I would welcome any contribution :)
