### ISSUE TITLE
Error clearing the filter: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by tsetsik** [leikind/wice_grid#158]
I'm having the same issue: as described here. https://github.com/leikind/wice_grid/issues/152
The params are: {"grid"=>"", "action"=>"show", "controller"=>"admin/categories"}

The controller code : @categories_grid = initialize_grid(Category)
The view code: 

<pre>
grid(@categories_grid) do |g|
          g.column name: 'ID', attribute: 'id' do |category|
            category.id
          end
          g.column name: 'Name', attribute: 'name' do |category|
            category.name
          end
          g.column name: 'Actions' do |category|
            link_to('Edit', edit_admin_categories_path(category))
          end
        end
</pre>

p.s I'm using rails 4.1, ruby 2.1 and the latest version for this gem

**Comment by leikind** [comment]
Ticket #152 was resolved by this commit:  https://github.com/leikind/wice_grid/commit/127b51a0a981cb74ef13d6e3a3b02c301c4c20f2 .

The fix should be present in version 3.4.3 .

Please specify the version you are using and paste the stacktrace of the error here.

**Comment by tsetsik** [comment]
I was on 3.4.2, sorry. After the update, everything is ok. Thanks
