### ISSUE TITLE
Parse.com support

### ISSUE THREAD

**Issue by junaid-malik-confiz** [leikind/wice_grid#159]
We are developing a rails app with backend db Parse.com. I have following questions
Is Parse.com supported?
Are all features are available for Parse.com as we have for MYSQL / Postgres.

Thanks
Junaid

**Comment by leikind** [comment]
I have no idea what parse.com is. Please see for yourself if the plugin suits your needs.

**Comment by junaid-malik-confiz** [comment]
thanks leikind for quick reply. I will check and explore it.

Junaid
