### ISSUE TITLE
Incorrect unicode characters

### ISSUE THREAD

**Issue by mirlord** [leikind/wice_grid#16]
During 'script/generate wice_grid_assets' I got the following (ruby 1.9.1):

vendor/plugins/wice_grid/lib/wice_grid.rb:161: invalid multibyte char (US-ASCII)
.....

And the same for the line 167. The reason is a two-byte chracter 'С' instead of 'C' in the word 'Column'. So, I mean... you know )) \u0421 instead of 43 (ASCII).

**Comment by leikind** [comment]
fixed :)
