### ISSUE TITLE
wrong sql for row count when filtering a joined table

### ISSUE THREAD

**Issue by matteolc** [leikind/wice_grid#164]
The models/controller/view:

```
  class Zone < ActiveRecord::Base
  belongs_to :atla

  class Atla < ActiveRecord::Base
  has_many :zones

  @zones_grid = initialize_grid(Zone, 
      per_page: 100,
      name: 'zones',
      include: :atla,
      enable_export_to_csv: true,        
      csv_file_name: 'zones'          
  )

  - g.column name: 'region'.titleize, attribute: 'region', model: Atla, custom_filter: :auto do |zone|
```

The error:
       Unknown column 'atlas.region' in 'where clause': SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM `zones`  WHERE (( atlas.region = 'Africa')) LIMIT 100 OFFSET 0) subquery_for_count):

How the query should be:
      SELECT  1 AS count_column FROM `atlas`  WHERE (( region = 'Africa')) LIMIT 100 OFFSET 0

Thanks!

**Comment by matteolc** [comment]
Actually the 'how it should be' ...

SELECT 1 AS count_column FROM zones WHERE ( atla_id IN (SELECT id FROM atlas WHERE( region = 'Africa')) LIMIT 100 OFFSET 0) subquery_for_count

**Comment by leikind** [comment]
Could you please check the latest 3.4.7 version?? I fixed an issue which could be the cause of this problem

**Comment by matteolc** [comment]
3.4.7 solved it -i did a gem update but was still using 3.4.2 doh
:+1: thanks all good now
