### ISSUE TITLE
Option for 'or' queries

### ISSUE THREAD

**Issue by akardes** [leikind/wice_grid#169]
Hi, I'm using wice_grid in a project with the external filters basically as a sort of advanced search feature. 

So, I was asked that if one has filters for several columns, would it be possible to make certain columns filter with an 'or' condition instead of an 'and' condition?
An additional flag or checkbox maybe that you can set per filter to mark that you don't want the results from this filter to exclude parameters from other filters.

E.g. you have a table for cars with columns like: model, color, price
And you want to set the 'or' flag on the price, so your filter query could be something like this:

``` sql
WHERE (model = "Ford" AND color = "beige") OR price <= 20000
```

Is this somehow possible with the current wice_grid version?

**Comment by leikind** [comment]
No
