### ISSUE TITLE
undefined method `<=' for #<ActiveSupport::OrderedHash:0xf070b34>

### ISSUE THREAD

**Issue by GarPit** [leikind/wice_grid#170]
This happens in method 'pagination_info' when I have 'group' in query.

```
if (! allow_showing_all_records) || collection_total_entries <= collection.length
```

In this case collection_total_entries is a Hash similar to this one:

```
{64=>1, 63=>1, 62=>1, 61=>1, 60=>1...
```

**Comment by leikind** [comment]
Show me your code please

**Comment by GarPit** [comment]
``` ruby
def initialize(repository = BackOfficeUser.scoped)
  @repository = repository.joins(:roles).joins(
    "INNER JOIN (VALUES #{roles}) as translated_roles(name, translated) ON back_office_roles.name = translated_roles.name"
  ).select("back_office_users.*, string_agg(translated_roles.translated, ', ') as translated_roles_names").group("back_office_users.id")
end
```

**Comment by leikind** [comment]
How is this code related to WiceGrid? Where is an `initialize_grid` call?

**Comment by GarPit** [comment]
Here it is:

``` ruby
@back_office_users_grid = initialize_grid(
  BackOfficeUser::FilterForSysAdminQuery.new.build(params[:search]),
  order: 'back_office_users.created_at',
  order_direction: 'desc',
  custom_order: {
    'back_office_roles.name' => 'translated_roles_names'
  }
)
```

**Comment by GarPit** [comment]
FilterForSysAdminQuery will call initialize and return ActiveRelation

**Comment by leikind** [comment]
I will take a closer look but I seriously doubt that WiceGrid can work correctly with `group`.

**Comment by GarPit** [comment]
Yes, seems you're right. But it's not so difficult to add support for this. I use this workaround:

```
        collection_total_entries_count = collection_total_entries.is_a?(Hash) ? collection_total_entries.count : collection_total_entries
```

**Comment by leikind** [comment]
As I do not have much time for this plugin I would welcome any pull request. Бельгийское пиво за мной :)

**Comment by GarPit** [comment]
Ok :+1:

**Comment by kabturek** [comment]
generally the problem is that collection.size returns a hash for grouped queries. collection.length returns the number of grouped records.

**Comment by GarPit** [comment]
Yes, exactly
