### ISSUE TITLE
Cannot set the icon for datepicker correctly in production (wice_grid 3.4.9)

### ISSUE THREAD

**Issue by fibers** [leikind/wice_grid#171]
The wice config defines a datepicker icon through 
Wice::Defaults::CALENDAR_ICON = "/assets/icons/grid/calendar_view_month.png"

When in production, the digest toggle is opened, so the datepicker cannot find the right png file .

Are there any workaround to fix it ?

**Comment by leikind** [comment]
https://github.com/leikind/wice_grid/issues/128#issuecomment-51446872
