### ISSUE TITLE
Support simple HTML5 date fields for filters

### ISSUE THREAD

**Issue by csm123** [leikind/wice_grid#181]
Modern browsers will place a datepicker in an input field marked with type="date", eliminating the need for jQuery DatePicker for date-only fields.

I would recommend adding this as an option for date filters, as the standard ones that Rails provides are unwieldy, and this would avoid having to add yet another JS (jQuery's date picker) to the app.

**Comment by leikind** [comment]
good idea

**Comment by eikes** [comment]
Here is a PR that does that: https://github.com/leikind/wice_grid/pull/194

**Comment by leikind** [comment]
3.4.11
