### ISSUE TITLE
Grid is broken in version 3.4.4 

### ISSUE THREAD

**Issue by fibers** [leikind/wice_grid#182]

**Comment by fibers** [comment]
And this won't be happened in development env, only appeared in production env

**Comment by leikind** [comment]
I don't understand. What is broken? What is this HTML code, and where should I be looking?

**Comment by leikind** [comment]
I cannot make any conclusions. I see no complete grid, I see no grid code. What is wrong in that HTML, I also don't see.

**Comment by leikind** [comment]
sorry, can't spend much time on it right now.

**Comment by fibers** [comment]
OK, thx, please take a look if you are free.

**Comment by leikind** [comment]
I am sorry, didn't have time to spend on wice_grid, really busy.  What was it?
