### ISSUE TITLE
Use a single checkbox for select/deselect all

### ISSUE THREAD

**Issue by jraoatlogic** [leikind/wice_grid#186]
It's very strange to have two checkboxes (actually clickable image) to do select/deselect all, I think it's much more common to have a single checkbox to do this. We can probably do some css/js trick to make the two clickable images look like one, but it would be much easier if this is provided out of box.

**Comment by leikind** [comment]
I agree. A pull request would be appreciated.

**Comment by cfiorini** [comment]
@leikind may be you can close this one so you don't get another pull request to handle :)

**Comment by leikind** [comment]
right :-)
