### ISSUE TITLE
How to use multiple order sql?

### ISSUE THREAD

**Issue by wayne5540** [leikind/wice_grid#188]
For example, how to add query like this:

```
Task.order("ship_date ASC, priority ASC, updated_at DESC")
```

Thanks.

**Comment by leikind** [comment]
The plugin does not support multiple `order by` currently.

**Comment by eikes** [comment]
There is some voodoo magic you can do to use multiple order clauses:

In stead of setting the order in the initialize_grid method call you set in on the `ar_options` object of the grid itself.

``` ruby
    @task_grid = initialize_grid(Task)
    @task_grid.ar_options[:order] = "ship_date ASC, priority ASC, updated_at DESC"
```

This setting will be overridden if another order is [set via the URL](https://github.com/leikind/wice_grid/blob/be30d1a1a475190f2f034726d725292f0ef2b9a3/lib/wice_grid.rb#L275-L279). 

This is of course not part of the official API so it may break in the future...

**Comment by djmolny** [comment]
And sure enough, the method [above](https://github.com/leikind/wice_grid/issues/188#issuecomment-72225628) doesn't work in Rails 5.2.
