### ISSUE TITLE
Icons not showing up on development (not production) 

### ISSUE THREAD

**Issue by pavoni** [leikind/wice_grid#190]
Only been using wice for a day - so quite possible I've not installed correctly, or made some other beginners mistake.

The functionality all seems to work pretty well - filters, sorting etc all working fine - but for some reason I can't see any icons in my table (using bootstrap if that makes any difference).

I saw the discussion here https://github.com/leikind/wice_grid/issues/128 (and tried the fixes) - but pretty sure my problem is elsewhere (and probably simpler).

Any pointers from the experts?

**Comment by leikind** [comment]
all icons should be fines but for the one for jQuery Datepicker. Did you run `rails g wice_grid:install`

**Comment by pavoni** [comment]
Pretty sure I did - but will run again.

The Datepicker is the one that does work!

**Comment by leikind** [comment]
weird

**Comment by pavoni** [comment]
Solved.
When I tried to load the paths directly they showed up as unloadable icons in my browser.
Turned out I hadn't correctly downloaded the files to \assets\images\icons\grid.
Thanks for the patient help!
