### ISSUE TITLE
Joined Tables - ActiveRecord::StatementInvalid - No such Column

### ISSUE THREAD

**Issue by patricklindsay** [leikind/wice_grid#193]
I want to list all Worksheets and have the ability to filter/order/sort by the name linked to a worksheet through a User object. I am getting a ActiveRecord::StatementInvalid stack trace. App is on Rails 4.1.6

```
# Error when trying to filter by associated object attribute
SQLite3::SQLException: no such column: users.name: SELECT COUNT(*) FROM "worksheets"  WHERE ((   users.name LIKE '%foo%'))
```

```
# User Model
belongs_to :worksheet
```

```
# Worksheet Model
has_one :user
```

```
# Controller
initialize_grid(Worksheet, include:  :user)
```

```
# View
  g.column name: 'Name', attribute: 'name', model: 'User' do |sheet|
    sheet.user.name if sheet.user
  end
```

I've followed the README and examples and can't seem to see what I am doing wrong?

**Comment by awanosik** [comment]
I'm having the same issue - it seems as though the joins aren't being added to the query - this is particularly odd as I just used this same functionality for another project a few weeks ago with no issue.

**Comment by leikind** [comment]
what WIceGrid version is it?

**Comment by awanosik** [comment]
I'm currently using 3.4.10.

**Comment by awanosik** [comment]
@leikind

I originally used 3.4.2 as per the READ.ME, then updated the gem later, but forgot to restart my rails server -- I'm assuming @patricklindsay's issue the same. I think this is related to https://github.com/leikind/wice_grid/issues/164  as it was failing on the SQL count statement

**Comment by leikind** [comment]
@awanosik so it is working with 3.4.10?

**Comment by leikind** [comment]
@awanosik 
correct,  3.4.7 is where this thing was fixed

**Comment by patricklindsay** [comment]
Thanks for the fast reply. Yes I was running 3.4.2, I've now upgraded to 3.4.10 and it's working. Great gem @leikind :+1:  
Now to fix those icons... ;)
