### ISSUE TITLE
ajaxification

### ISSUE THREAD

**Issue by leikind** [leikind/wice_grid#2]
Ability of WiceGrid to reload itself inside its container

**Comment by tayfunoziserikan** [comment]
When do you plan to start this work ? Thank you.

**Comment by onurozgurozkan** [comment]
:+1:  This feature will be very nice but should be support turbolinks which is default gem at Rails 4.x

**Comment by leikind** [comment]
I was actually going to experiment with turbolinks or  pjax alone to see how it is possible to integrate wice_grid with them. So I don't have a good answer to your question.
