### ISSUE TITLE
Formatting page controls

### ISSUE THREAD

**Issue by hdotson1** [leikind/wice_grid#200]
I am having trouble seeing how to format the pagination controls. Instead of coming out the way they are in the examples  like:  1  2  4 5 .....100 101 >>>
its being displayed as a bulleted list, like this:
1
2
3
...
101
102

How do I make it display horizontally?

**Comment by leikind** [comment]
use a web inspector / dev tools of your browser to compare styles in the examples with your page and find out which styles are missing in your case.

**Comment by hdotson1** [comment]
Thanks for the quick reply!

I grabbed the wice_grid.css.scss  which defines the pagination class and is affecting my view. What classes do I need to modify to make it look like the example page controls? I know enough CSS to do most of the formatting but I'm having trouble making the numbers display horizontally.

**Comment by leikind** [comment]
I am sorry, you are on your own fighting css of your website / webapp. This has nothing to do with the plugin itself.

**Comment by hdotson1** [comment]
Alright. Thanks anyway.
