### ISSUE TITLE
Export CSV Replaces database table names with Grid Table Header names

### ISSUE THREAD

**Issue by CromonMS** [leikind/wice_grid#205]
Been getting my head around Wicegrid, really nice for what I need, however; after I export a csv of the grid, when I try to then re-import it the headers aren't compatible with the database anymore.

Anyone got any ideas?
TIA.

**Comment by leikind** [comment]
> Export CSV Replaces database table names with Grid Table Header names

CSV export gives you a CSV version of your HTML view, it is not supposed to make a DB dump for you. Use your database dump tools, or process your csv the way you need.

**Comment by CromonMS** [comment]
Ahh thanks for getting back, I'm pretty novice to Rails, so will do some more learning :)
