### ISSUE TITLE
Wice grid working on one controller and not working on another controller

### ISSUE THREAD

**Issue by ddpdevang** [leikind/wice_grid#207]
The problem that I have is my grid is working on one controller that is products while not working on the invoices controller...

Dont understand what the problem really is... DOne everything the same way...

Gem version that I am using is latest...

**Comment by leikind** [comment]
Normally when submitting any report you should give the controller code for the grid, the view code, and any error stacktraces if present.

**Comment by leikind** [comment]
No  information given, closing

**Comment by ddpdevang** [comment]
---

## invoices_controller.rb

``` ruby
 def index
    @invoices = initialize_grid(Invoice)
  end
```

---

## index.html.erb

```
<p id="notice"><%= notice %></p>
<%- model_class = Invoice -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= grid(@invoices, show_filters: 'always') do |g| 

  g.column name:  'Due Date' do |task| 
    h task.send("due_on")
  end 
  g.column name:  'Status' do |task| 
    @statusValsMap[task.Status] 
  end
  g.column name:  'Amount' do |task| 
    number_to_currency task.total*0.01, {:unit => "£"}
  end 
  g.column name:  'Cutoff' do |task| 
    h task.send("cutoff_on")
  end 
  g.column name:  'Show' do |task|
    link_to('Show', task )
  end
  g.column name:  'Edit' do |task|
    link_to('Edit',:action => 'edit', :id => task )
  end
  g.column name:  'Destroy' do |task|
    link_to('Destroy',{ :action => 'destroy',:id =>task}, :confirm => 'Are you sure?' )
  end
 end -%>

<br>

<%= link_to 'New Invoice', new_invoice_path %>
```

**Comment by ddpdevang** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/888723/7267321/d5503e1e-e8d6-11e4-831a-ab6d6d500e4b.png)

![screenshot-1](https://cloud.githubusercontent.com/assets/888723/7267331/fce8bd3e-e8d6-11e4-9ba7-7458b7e64df0.png)

**Comment by ddpdevang** [comment]
Below is  the screenshot of the thing on one controller where it is working:

![screenshot-2](https://cloud.githubusercontent.com/assets/888723/7267477/8ef156da-e8d9-11e4-9b51-76d103f4cfeb.png)

Please Help

As it is getting more and more critical to have this working

**Comment by leikind** [comment]
Please copy paste the HTML source code of both pages somewhere, for instance, into github gists.

**Comment by ddpdevang** [comment]
https://gist.github.com/ddpdevang/92978cdfdd74e3e4fcdd

https://gist.github.com/ddpdevang/a63372bb01b7318a059a

**Comment by leikind** [comment]
I meant the HTML  code of the page, not ERB templates

**Comment by ddpdevang** [comment]
Please check the links again...

**Comment by leikind** [comment]
Why is your page https://gist.github.com/ddpdevang/a63372bb01b7318a059a incomplete, there is no <html> declaration, there is no html header with all `<script src=""></script>`  tags? Of course this page won't work.

**Comment by ddpdevang** [comment]
I dont understand why that is not coming... the template for both the layout is the same then also...

Any clue on why it might not be coming

**Comment by leikind** [comment]
I have no idea, and why you have no layout for a certain controller has absolutely no relation to WiceGrid. WiceGrid cannot work without its JavaScript file. I help solve WiceGrid problems.
