### ISSUE TITLE
group omitted from ar options

### ISSUE THREAD

**Issue by ghost** [leikind/wice_grid#21]
Hi Yuri,

I would like to be able to pass a group option to the wice grid options because I want to display sums in my resultset. Glancing over the code, I see no particular problem why GROUP BY might be omitted from the available wice grid options. It could be passed along just like conditions or select.

Was there any reason I might be overlooking which led you to not include the GROUP BY option? If not, I'll try to give it a shot.

Thank you 
Ben

**Comment by leikind** [comment]
Hi Ben,

No, there wasn't any particular reason to exclude GROUP BY, just because I had never needed it in WiceGrid, so I'd never thought about it. Please feel free to fork and experiment.

Yuri

**Comment by ghost** [comment]
Hello Yuri,

thank you for the quick answer. I will go ahead then. Thank you for wice grid, it is worth to use rails just for your plugin alone!

**Comment by leikind** [comment]
Thanks!

**Comment by leikind** [comment]
added the ActiveRecord :group option: http://github.com/leikind/wice_grid/commit/ef6b67a1d60e664a72136f61a6d311dcfa00cce9
