### ISSUE TITLE
Custom Filter for "Status" attribute... 

### ISSUE THREAD

**Issue by ddpdevang** [leikind/wice_grid#215]
I have the status  vals stored in database as integer vals, like below:

``` ruby
@statusVals = {"New" => 1, "Paid" => 2, "Cancelled" => 3 }
@statusValsMap = {1 => "New", 2 => "Paid", 3=> "Cancelled" }
```

So what I want to do is have different key and value for the dropdown?

What I am currently doing is below:

``` ruby
g.column name:  'Status',attribute: 'Status', custom_filter: %w(New Paid Cancelled), auto_reload:  true do |task| 
    @statusValsMap[task.Status] 
  end
```

What should I do in custom filter that its value when selected is integer which is in the database and its displays the different values??
http://wicegrid.herokuapp.com/custom_filters2

**Comment by leikind** [comment]
It's written in the documentation: https://github.com/leikind/wice_grid#array-of-two-element-arrays-or-a-hash

http://wicegrid.herokuapp.com/custom_filters2 is also the answer.
