### ISSUE TITLE
General questions about this gem

### ISSUE THREAD

**Issue by onebree** [leikind/wice_grid#217]
1. Is Rails 4 (4.2.0) supported in full?
2. On the heroku app, I see that the _grids partial is written in erb. Is it possible to write it in haml instead? (The rest of our pages are haml, and we would like to keep it that way.)
3. Right now, we use bootstrap 3.3.4 striped tables. The only borders are bottom of the header row, if present.
   - Can I style wice_grids to remove entire-cell borders?
   - I also want to style a surrounding table border, as if you put a bootstrap table inside a panel.
4. Is this gem compatible with [rails-bootstrap-form](https://github.com/bootstrap-ruby/rails-bootstrap-forms) gem? We use this heavily in our views.

**Comment by leikind** [comment]
1. I can't say for sure, none of my applications uses 4.2.0 yet
2. Yes, you can, but this will look ugly. I use HAML everywhere I can and I love it, but if you think about it, WiceGrid grids are nothing but big helpers, i.e., chunks of Ruby code, and I see no point in writing Ruby code in HAML. You might even consider putting grids into view helpers, but I prefer leaving them in partials. To me they are a special type of view files.
3. This is just HTML, style it the way you want
4. I have no idea, never used  rails-bootstrap-form, and I don't even understand the question. What should WiceGrid grids do to be compatible with some form gem, and why?

**Comment by leikind** [comment]
4.1 is supported

**Comment by onebree** [comment]
(4) You can disregard that one... I thought we used bootstrap-forms gem for tables, but no. We just use standard rails forms on tables on our index pages.

**Comment by onebree** [comment]
(5) What is the contents of class `Task` that you keep referencing in the index?

**Comment by leikind** [comment]
Just part of a fake data model to showcase the plugin https://github.com/leikind/wice_grid_examples/tree/master/app/models

**Comment by leikind** [comment]
wrong link
here is the correct one https://github.com/leikind/wice_grid_testbed/tree/master/app/models

**Comment by onebree** [comment]
Thank you... I am just trying to see how I can easily use this in our Rails 4.2, Bootstrap 3 project. Right now we use `sorttable.js`, but for some reason it does not work properly. The script loads, but if reload then navigate to a new page, the script fails.

Just trying to figure out the best alternative to sorting column headings in our app

**Comment by leikind** [comment]
You are welcome, have fun :-)
