### ISSUE TITLE
Undefinedcolumn because wicegrid converting attribut name to lowercase

### ISSUE THREAD

**Issue by ddpdevang** [leikind/wice_grid#218]
The problem is that wice_grid is converting my column name to lowercase as shown in screenshot...

My actual column in the database is "SpouseName", where else it is searching for spousename so the filters are not workig because of that.

Any solution to it, without changing the column name in database to that in lowercase

![screenshot](https://cloud.githubusercontent.com/assets/888723/7441297/120b57aa-f0ff-11e4-9628-44023e2e6c57.png)

**Comment by leikind** [comment]
Have a closer look at the error message and the sql. The sql code being executed mentions contact.SpouseName, it's correct, there is no case conversion happening.

Also, CameCase fields in Rails are disgusting and tasteless.
