### ISSUE TITLE
Custom styling for wicegrid 3.0.4

### ISSUE THREAD

**Issue by clubbavi** [leikind/wice_grid#221]
Hello,

I am using wicegrid 3.0.4 with rails 3. I want to do a custom styling.
I added ":html => {:style => 'text-align: center'}  or  html: {style: 'text-align: center'}"  as:

```
g.column :column_name => "Name", :attribute_name => 'name', html: {style: 'text-align: center'}"
```
- It gives me "Unknown key: html". 
  How can I add custom styles or classes?

Thanks.

**Comment by leikind** [comment]
Can you post the whole grid definition?

**Comment by clubbavi** [comment]
Code Snippet:

```
 <%= grid(@list) do |g|
   g.column :column_name => "Name", :attribute_name => 'name'
   g.column :column_name => "Size", :attribute_name => 'size', html: {style: 'text-align: center'}
 end -%>
```

It gives me "Unknown key:html" error.

**Comment by leikind** [comment]
You are using a version from 2011 https://rubygems.org/gems/wice_grid/versions and using documentation for the latest version. There is no `html` in 3.0.4. Read the docs inside the gem.

**Comment by clubbavi** [comment]
What is the attribute to use styling in wicegrid 3.04
?

**Comment by leikind** [comment]
Read the docs inside the gem.

**Comment by clubbavi** [comment]
Ok got it. 
Have to use like this : 

```
:td_html_attrs => {:style => 'text-align: right'}
```

Thanks
