### ISSUE TITLE
Invisible Column

### ISSUE THREAD

**Issue by kris-redfall** [leikind/wice_grid#224]
Would be nice to be able to set a column to invisible, but still create an external filter on that column (for example).  

E.g. you could have a toggle on a boolean column to only show the TRUE or FALSE rows without needing to waste a column to show TRUE/FALSE. 

I can think of lots of other uses for an invisible column, basically I would want the data to be there in the query, just not in the view.

**Comment by leikind** [comment]
I don't see why you can't do this with css and javascript. I implemented this for one project, the filters were external.
