### ISSUE TITLE
can't get #read method successfully, after I initialize a ActiveRecord with initialize_grid. Always tell me  "undefined method `[]' for nil:NilClass", and hove no either reminder 

### ISSUE THREAD

**Issue by winterbang** [leikind/wice_grid#227]
I guess that there is some bug in the method  “form_ar_options” of class Wice::WiceGrid

**Comment by leikind** [comment]
I need to see the code and stack traces. I do not possess telepathy skills.

**Comment by leikind** [comment]
Also the version number

**Comment by winterbang** [comment]
``` javascript
def income_expenses
    @freports = initialize_grid(Freport.active_null,
      :order => 'freports.created_at',
      :include => [:doctor, :order],
      :csv_file_name => 'projects'
    )
    @freports.read
end
```

![1a3c2ec4-4766-4b9a-9491-5fe25d1ad64e](https://cloud.githubusercontent.com/assets/4116465/8100630/1074ce4c-1041-11e5-9650-bcaa6a5d9414.png)

**Comment by winterbang** [comment]
## version  3.4.2

**Comment by winterbang** [comment]
thanks!

**Comment by leikind** [comment]
Please remove the call to read. You don't need it. There is no `#read` in examples. And what you attached is not a stacktrace.

**Comment by winterbang** [comment]
@leikind How can I get ActiveRecord::Relation of Freport after filter. Is there provided method?

**Comment by leikind** [comment]
I am not sure I understand.Please elaborate

**Comment by winterbang** [comment]
I am sorry for my terrible English.

```
def income_expenses
    @freports = initialize_grid(Freport.active_null,
      :order => 'freports.created_at',
      :include => [:doctor, :order],
      :csv_file_name => 'projects'
    )
    @freports.read
end
```

This code will filter Freport record.  But   the `@freports` is not ActiveRecord Relation  instance.  I want get the object of record of filter via the object of @freports.

**Comment by winterbang** [comment]
is there any methodes for this?

**Comment by leikind** [comment]
This is how you do it:  http://wicegrid.herokuapp.com/resultset_processings2

REMOVE `@freports.read`!

**Comment by winterbang** [comment]
ok, thanks
