### ISSUE TITLE
uninitialized constant Wice::JsAdaptor

### ISSUE THREAD

**Issue by ghost** [leikind/wice_grid#23]
I'm using latest wice_grid with Rails 2.3.8. Error log:

 Showing app/views/layouts/application.html.erb where line #10 raised:

uninitialized constant Wice::JsAdaptor

Extracted source (around line #10):

7: 
8: <%= stylesheet_link_tag 'formtastic', 'formtastic_changes' %>
9: <%= javascript_include_tag :defaults %>
10: <%= include_wice_grid_assets %>
11: <%= yield :head %>
12: <link rel="shortcut icon" href="/favicon.ico">
13: <link rel="icon" href="/favicon.ico" type="image/vnd.microsoft.icon">

RAILS_ROOT: /home/max/Rails/cts2
Application Trace | Framework Trace | Full Trace

/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:440:in `load_missing_constant'
/opt/ruby-enterprise-1.8.7-2010.02/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:80:in`const_missing'
/home/max/Rails/cts2/vendor/plugins/wice_grid/lib/helpers/wice_grid_misc_view_helpers.rb:62:in `include_wice_grid_assets'
/home/max/Rails/cts2/app/views/layouts/application.html.erb:10:in`_run_erb_app47views47layouts47application46html46erb'
/home/max/Rails/cts2/app/controllers/records_controller.rb:27:in `index'

---

I have not found the JsAdaptor declaration in the plugin files. 
Thanks god I don't need calendar widget :)

**Comment by leikind** [comment]
Hello.
Thanks for the report. Please git pull, should be working now.
Somehow some changes had been committed to the wrong branch, to master, instead of another bleeding edge branch.
