### ISSUE TITLE
SUM column and ordering

### ISSUE THREAD

**Issue by ghost** [leikind/wice_grid#24]
Hello Yuri,

another thing I just ran into: I have a few grids where there are functions as columns, i.e. sum, like this

SELECT ..., SUM(QUANTITY) AS QTY_SUM, ...

Now in the grid, I am not able to sort this column because the column isn't an attribute, but the result of a calculation on an attribute.
MySQL itself has no problems doing an ORDER BY SUM(QUANTITY), but I have no idea how to get Wice Grid to bypass the check if the column name is present. Is there a way? If not, it would be great to have this feature, as it is often needed, and I hereby request it.

Thank you

**Comment by leikind** [comment]
Hello,
Have you tried using custom ordering, like in this example: http://grid.leikind.org/custom_ordering
:custom_order  in the grid_initialize overrides the column name by custom SQL.
Docs - http://leikind.org/apis/wice_grid/files/README_rdoc.html#customordering
Let me know if this doesn't solve the problem for you.
Thanks for the feedback.

**Comment by ghost** [comment]
Hello Yuri, thank you. Turns out this was a very bad case of RTFM on my part. Works like a charm! Ben

**Comment by leikind** [comment]
It's OK, the API is big.

**Comment by hakunin** [comment]
It would be nice if virtual columns waere supported, even if I need to do a little bit more config. 
I have to create a view now, hopefully wice grid supports that.

**Comment by leikind** [comment]
@hakunin virtual columns are not supported

**Comment by hakunin** [comment]
Would it be hard to support them? 
I can either work around not having them, or fork the gem and try to add the support.
In my current project I need a lot of them.

**Comment by leikind** [comment]
Please read the first sentence of README.md https://github.com/leikind/wice_grid/blob/rails3/README.md

**Comment by hakunin** [comment]
Sorry, I am not asking you to do it. I am asking because I want to try implementing it.

**Comment by leikind** [comment]
Sure you can give it a try. I have a very vague idea of how this can be implemented though, as this plugin was very DB centric from the very start
