### ISSUE TITLE
Date filter issue

### ISSUE THREAD

**Issue by thoberre** [leikind/wice_grid#251]
Hi, 

I noticed a datefilter issue in my application v3.5.0 and checked against http://wicegrid.herokuapp.com 3.6.0pre seeing the same behaviour.

In the date/datetime helper example i get one date to many in my results. Should I not get only items for 24.03.2013 in this filter or am I missing something?

![image](https://cloud.githubusercontent.com/assets/4928612/9556070/28e91964-4dd2-11e5-88c8-9aeccbb8e077.png)

**Comment by leikind** [comment]
Please have a look at 3.6.0.pre4, it should be fixed.

**Comment by thoberre** [comment]
Looks good - thanks!
