### ISSUE TITLE
how to deal with two or more table (left  join,inner join etc) 

### ISSUE THREAD

**Issue by testzlx** [leikind/wice_grid#253]
i have seen your referrrences ,but i still can not understand how to use include: or join: ,can you give me some tips?        --------a li ga duo(japanese pronunciation)

**Comment by leikind** [comment]
Here is a working example with code
http://wicegrid.herokuapp.com/joining_tables

**Comment by testzlx** [comment]
you are a very very good man  !

**Comment by leikind** [comment]
good luck writing your code
