### ISSUE TITLE
Auto detect column name from i18n data if attribute given

### ISSUE THREAD

**Issue by zuf** [leikind/wice_grid#254]
It would be nice if the wice_grid could use name for column from I18n attribute names like that:

``` ruby
g.column attribute: 'last_name'
```

could means something like this

``` ruby
g.column attribute: 'last_name', name: t('activerecord.attributes.users.last_name')
```

**Comment by leikind** [comment]
I am against it. I prefer less magic, and I want to have a option to have no names at all.
