### ISSUE TITLE
How to mark action_column as selected?

### ISSUE THREAD

**Issue by kai-breitbarth-zz** [leikind/wice_grid#261]
How it is possible to mark an action_column as selected?
Would be nice if in the controller something like
@selected = ["2", "34, "78"] 
is possible to pre-select rows with the action_column

**Comment by leikind** [comment]
You can easily do this with javascript

**Comment by leikind** [comment]
1) Add a css class to  grid rows  you want to pre-select

``` ruby
 g.column ... do |rec|
  if ...
    [rec.foo , {class: 'your-preselect-class'}]  # will add this class to <tr>
  else
      rec.foo
  end
end
```

Example: http://wicegrid.herokuapp.com/styling

2) then in JS on dom:loaded:

``` js
$('.your-preselect-class .sel input').prop('checked', true)
```

**Comment by leikind** [comment]
made some errors in the initial code, please refresh

**Comment by kai-breitbarth-zz** [comment]
ugly

**Comment by leikind** [comment]
This is called web development. 

Bloated APIs are ugly.

**Comment by kai-breitbarth-zz** [comment]
True. But it would be nicer if auto_column would recognize something like @selected by itself.
This way I wouldn't need javascript.
I implemented it yesterday and it works. But you need to use row_attributes to get the class at the tr-tag:

``` ruby
g.row_attributes do |c|
    if @selected && @selected.include?(c.id.to_s)
      {class: 'preselected-row'}
    end
 end
```

And a little coffee script

``` javascript
$(document).ready ->
    $('.preselected-row .sel input').prop 'checked', true
```

Maybe it's worth to mention it in your example page.
Btw. don't get me wrong, I really like this framework!

**Comment by leikind** [comment]
That's almost exactly how I suggested it, I think I made a mistake by not choosing `row_attributes`, but the idea is the same. I see no problem in this approach. But if you feel like adding such a feature to auto_column I would be willing to accept a pull request

**Comment by Obi-TOB** [comment]
Thanks for this. Works good. However it fails when the grid is refreshed by setting a filter. Did you find a solution for this as well?

Best
