### ISSUE TITLE
Export to CSV doesn't start download but renders tempfile path

### ISSUE THREAD

**Issue by ghost** [leikind/wice_grid#27]
Hi,

another problem I have run into: In my new application (Rails 2.3.8), I have enabled export_to_csv. When clicking the export button, there is no file download starting, but the only thing that happens is a new page with only the path to the tmpfile (the csv) rendering in the view, something like:

/var/folders/3N/3NYKFtItHaCuQL6h0KVbkk+++TI/-Tmp-/channels_7068020100831-1170-x3xr6a-0

for my grid named "channels".

I have browsed the code a bit but I cannot see the actual call to send the csv to the browser. If possible, I would like to use apache's x-sendfile for sending the data, but of course getting it to work at all is the priority.

Thank you for looking into this.

**Comment by leikind** [comment]
Could you please post grid related code from the controller?

**Comment by ghost** [comment]
Hi, here it is:

def index
    @grid = initialize_grid(User,
      :select => "users.id,products.id,products.releasedate,products.ean,products.contract_code,products.contract_id,products.articleno,products.articlegroupcode,products.artist,products.title,products.label,products.deleted",
      :order => "products.releasedate",
      :order_direction => 'desc',
      :conditions =>  ["user_products.user_id = ? AND users.id IN (?)",current_user.id,current_user.id],
      :joins => "LEFT OUTER JOIN `user_products` ON (`users`.`id` = `user_products`.`user_id`)
                 LEFT OUTER JOIN `products` ON (`products`.`id` = `user_products`.`product_id`)",
      :name => 'catalog',
      :enable_export_to_csv => true,
      :csv_file_name => 'catalog'
    )
  end

Nothing non-standard in the controller.

**Comment by leikind** [comment]
Please finish your action with a call to export_grid_if_requested.

Read attentively here: http://leikind.org/apis/wice_grid/files/README_rdoc.html#csvexport
and here: http://leikind.org/apis/wice_grid/classes/Wice/Controller.html#M000014

Loot at the controller code here: http://grid.leikind.org/csv_export

**Comment by leikind** [comment]
closing

**Comment by ghost** [comment]
Sorry for the delay. Thank you for your patience. I misinterpreted the "should" in the documentation meaning it is an optional call. After adding it, now it works.
