### ISSUE TITLE
Support Boostrap 3 Datepicker

### ISSUE THREAD

**Issue by zedtux** [leikind/wice_grid#274]
As far as I can see, the is already a supported version of a date and time picker for bootstrap which is supported in addition to the jQuery plugin.

Here is another one : http://eonasdan.github.io/bootstrap-datetimepicker/.
It would be cool to increase the compatibility of the `wice_grid` gem with this one too.

**Comment by leikind** [comment]
thanks for the tip, but I will not do this. I will accept PRs though, and guide contributors around the code

**Comment by leikind** [comment]
Also, adding any new datepicker only increases incompatibility if you know what I mean. And there are many many things to take care about when adding a new datepicker: autoreload, external filters, documentation...

**Comment by zedtux** [comment]
I got your point, but in the other hand, the guy who comes and use `wice_grid` with another datetime picker and is working out of the box, will be super happy.

I have started to implement it, I got the logic in the code to add it, and year there is a lot todo but I'll try.

**Comment by leikind** [comment]
You made me smile :)
I don't use this plugin these days, I am tired of supporting it for many many years, and I need my time for other things which interest me more. So the only thing I can give ti users of WiceGrid is guidance, advice,  and testing pull requests.

**Comment by zedtux** [comment]
Have you received contributors candidacy in order to help you on this project ?
This gem is awesome, if you can't, someone else should help you to maintain it.

Anyway, I'll do my best to get this datetime picker working and you'll see if you accept it or not :yum:

**Comment by leikind** [comment]
Yes, if someone could maintain it that would be awesome and I would be ready to help when time allows (which is mostly weekends). This someone should understand the point of the plugin though, its scope...

**Comment by zedtux** [comment]
I'm crossing fingers for you having this someone coming one day.

**Comment by zedtux** [comment]
@leikind the other version of the bootstrap datetime picker I'm implementing is really close to the existing one, so I guess all will work out-of-the-box more or less.

I was looking at the testbed repo for tests with the existing bootstrap calendar but I don't find them. Can you please confirm there are no tests for the existing bootstrap plugin ?

If it's the case, maybe the first step is to extract the existing tests of the jQuery calendar in a folder `jQuery` and then duplicate them in a `boostrap-datepicker` and make then passing, don't you think ?
Then I could duplicate the `boostrap-datepicker` folder in a `boostrap-datetimepicker` and make the tests passing so that we're sure all is working fine.

**Comment by leikind** [comment]
there are no tests for the existing bootstrap plugin

> Then I could duplicate the boostrap-datepicker folder in a boostrap-datetimepicker and make the tests passing so that we're sure all is working fine.

I think you can't have both  jQuery calendar AND  boostrap-datepicker in the same application, if I am correct, how do you deal with this?

**Comment by zedtux** [comment]
Well it should be possible to reload the conf between different tests. Sounds not easy to feasible in my opinion.

**Comment by zedtux** [comment]
I'm no more working on it, sorry.
