### ISSUE TITLE
How to use bootstrap_datetimepicker

### ISSUE THREAD

**Issue by clubbavi** [leikind/wice_grid#283]
In wice grid to pick a datepicker we can use :filter_type WiceGrid doc mentioned 4 types `:rails_datetime_helper` `:rails_date_helper` `:jquery_datepicker` `:bootstrap_datepicker`

how to use bootstrap_datetimepicker ?

for eg:-`g.column :name => 'Date/Timing', :attribute => 'date', filter_type: :datetime_picker`

Any help will be appreciated

Thanks

**Comment by leikind** [comment]
First you answer your own question listing 4 possible correct values of `filter_type`, and then you come up with `filter_type: :datetime_picker`... Where did you find `datetime_picker`?

It's all in the docs here and here https://github.com/leikind/wice_grid#date-and-datetime-filters and here https://github.com/leikind/wice_grid#installation

**Comment by leikind** [comment]
to use bootstrap_datetimepicker you have to add its support to WiceGrid first.

**Comment by clubbavi** [comment]
in doc it is said Bootstrap datepicker works for datetime, too. But how can I add time to the picker as in   (http://eonasdan.github.io/bootstrap-datetimepicker/) if I want to use bootstrap datetime picker. How can I configure it?

**Comment by leikind** [comment]
Ok, I understand now. I am sorry for misunderstanding, and I am sorry for the misleading documentation.

> :bootstrap_datepicker - Bootstrap datepicker (works for datetime, too)

here https://github.com/leikind/wice_grid#date-and-datetime-filters means that this picker will work if your DB column is datetime, but it doesn't mean the datepicker will show any time controls. The last time I checked Bootstrap datepicker is a **date** picker, and it doesn't have any time related functionality.

I will make it clearer in the docs

**Comment by clubbavi** [comment]
So, is it possible to add a time to the picker or add bootstrap datetimepicker dependency to the wicegrid? Any configurations I need to do to show time in the picker?

**Comment by leikind** [comment]
wicegrid does not support  bootstrap datetimepicker

**Comment by clubbavi** [comment]
Ok, so currently I can use only the default time which comes in dropdown. It would be great if wicegrid supports datetime picker as well.

**Comment by leikind** [comment]
Yes it would be great, but I don't plan to do it. This plugin is in support mode and is looking for contributors. I accept good PRs though

**Comment by clubbavi** [comment]
Sure. I will try to help.
