### ISSUE TITLE
Filtering among cyrillic data is case sensitive

### ISSUE THREAD

**Issue by marat-y** [leikind/wice_grid#292]
Filtering among cyrillic data is case sensitive. Is there anyway I can get around this?

**Comment by leikind** [comment]
which DB are you using?

**Comment by marat-y** [comment]
sqlite

**Comment by leikind** [comment]
even in production? 😼

**Comment by leikind** [comment]
http://stackoverflow.com/questions/15480319/case-sensitive-and-insensitive-like-in-sqlite

**Comment by leikind** [comment]
you can also change the SQL operator used for matching strings in string filters: https://github.com/leikind/wice_grid/blob/rails3/lib/generators/wice_grid/templates/wice_grid_config.rb#L49

**Comment by marat-y** [comment]
But filtering english text is not case-sensitive, while filtering russian text (cyrillic letters) is case-sensitive.

**Comment by leikind** [comment]
I fail to understand what WiceGrid has to do with an Sqlite problem? WiceGrid uses ActiveRecord, you are using Sqlite, you should be looking for the answer to your question elsewhere.
