### ISSUE TITLE
RuboCop: Unnecessary utf-8 encoding comment.

### ISSUE THREAD

**Issue by noahc** [leikind/wice_grid#296]
I'm trying to get the tests in a state that I can have confidence that the feedback I receive is valid for any changes I make. When I run RuboCop, I get a significant amount of errors. Here is an example...

```
lib/wice/wice_grid_serialized_queries_controller.rb:1:1: C: Unnecessary utf-8 encoding comment.
# encoding: utf-8
```

Consulting: http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Encoding, It suggests that these encodings aren't needed for 2.0+ versions of Ruby. Consulting the `.travis.yml` file, it appears the oldest version we're testing against is 2.0. 

I'm happy to issue a pull request for this, but it seems safe to remove these. The other option is to change the rule, which I can do as well. Any thoughts on which way to go?

**Comment by ghost** [comment]
close?
