### ISSUE TITLE
Seems to be incompatible with Rails 5

### ISSUE THREAD

**Issue by ghost** [leikind/wice_grid#308]
The grids produced by wice_grid don't seem to work in Rails 5 yet. They produce the error "wrong number of arguments (given 0, expected 1)". See: http://stackoverflow.com/q/38229373.

**Comment by leikind** [comment]
that it true. No work has been done to support Rails 5, and no work is planned.

**Comment by dima4p** [comment]
why?

**Comment by davidwessman** [comment]
Need contributors and testers.

**Comment by leikind** [comment]
Well, I don't want to work on it anymore. Sorry for all the people who depend on it, but no, no more.

**Comment by dima4p** [comment]
Hello, Юрий @leikind. I'm going to try to fix this problem. Do you have any guidance that can help me?

**Comment by dima4p** [comment]
Maybe someone has too?

**Comment by hpeterka** [comment]
Wice grid seems to work, when you use git code instead of latest release of gem in your Gemfile:
`gem 'wice_grid', '> 3.6', git: 'https://github.com/leikind/wice_grid.git', branch: 'rails3'`

**Comment by dima4p** [comment]
Use v6.1.3
