### ISSUE TITLE
Date filter and timezone

### ISSUE THREAD

**Issue by iva2k** [leikind/wice_grid#31]
It appears that the dates entered into the datetime filter are UTC, while the grid shows the datetimes in timezone set by config.time_zone

I fiddled around, and this change to the wice_grid_config.rb seems to be sufficient to make it honor the config setting:

```
  Wice::Defaults::DATETIME_PARSER = lambda{|datetime_string| Time.zone.parse(datetime_string) }
```

(Using Time.zone.parse instead of DateTime.parse)
Same change looks appropriate for DATE_PARSER.

**Comment by leikind** [comment]
I guess that for parsing dates it should be

```
     Time.zone.parse(date_string).utc.to_date
```

to catch cases like 

```
 ruby-1.8.7-p302 > Rails.configuration.time_zone
  => "Mexico City" 
 ruby-1.8.7-p302 >  Time.zone.parse('2010-11-16 23:00 ').day
  => 16 
 ruby-1.8.7-p302 >  Time.zone.parse('2010-11-16 23:00 ').utc.day
  => 17 
 ruby-1.8.7-p302 >  Time.zone.parse('2010-11-16 23:00 ').utc.to_date
  => Wed, 17 Nov 2010 
```

**Comment by leikind** [comment]
No, this is wrong of course. 
If the user says the 16th of September he means the 16th of September and timezones should not interfere.
I think dates should be left as they are.

What do you think?

**Comment by leikind** [comment]
http://github.com/leikind/wice_grid/commit/369f0f41b253839be3bd7bec82e488c03d579b6b

**Comment by iva2k** [comment]
DATE_PARSER is OK with Date.parse(), I agree. My last blurb "Same change looks appropriate for DATE_PARSER." was incorrect.

**Comment by leikind** [comment]
closing
