### ISSUE TITLE
Preparing for Rails 5 - how can we do this?

### ISSUE THREAD

**Issue by davidwessman** [leikind/wice_grid#311]
To start, @leikind many thanks for developing and maintaining this wonderful gem! I understand that you will not continue to support this gem and I would like to see if the community can continue your work.

I have two questions:
1. Is there any active maintainers or anyone with privileges?
2. Which changes are needed to gain Rails 5 compatibility?

It would be great if we can start making some PRs to move towards Rails 5 compatibility and to find a way to maintain the gem in the same trip.

**Comment by leikind** [comment]
1. There are people submitting PRs, but there are no people who maintain the gem on regular basis, so probably the answer is No. No, there are no people with privileges.
2. I don't know

**Comment by davidwessman** [comment]
@leikind Will you be able to merge PRs and such? Is there anyone you could think of getting privileges?

The second question would require some debugging from the community

**Comment by leikind** [comment]
I do merge PRs, but I don't have time for extensive testing. 

If there is a committer whose understanding of how the plugin works is not superficial and who is willing to spend their time on it I would of course grant necessary permissions.

**Comment by dima4p** [comment]
Use v6.1.3
