### ISSUE TITLE
Wicegrid 3.6.0.pre4 isn't working with Turbolinks 5.0.0

### ISSUE THREAD

**Issue by maurymmarques** [leikind/wice_grid#313]
Download CSV files and filters are not working.

My Gemfile is like that

```
gem 'rails', '4.2.6'
gem 'turbolinks', '~> 5.0.0'
gem 'wice_grid', '3.6.0.pre4'
```

When I click on a link from the website and then try filter out something on the grid, the last action does nothing.
To solve that problem I added this to my CoffeeScript file and it worked.

```
$ () -> 
    $(document).on "turbolinks:load", ->
        initWiceGrid()
```

But I could not solve another problem...
When I click to export a CSV file, the report content is being loaded into the browser instead of start downloading the file.

**Comment by davidwessman** [comment]
No progress has been made towards Rails 5 or Turbolinks, would be great if you can look into it :+1:

_Edit:_
With _you_ I mean @maurymmarques

**Comment by leikind** [comment]
And I am not going to.

Please read the first lines of the readme file: https://github.com/leikind/wice_grid

**Comment by miqs1992** [comment]
I had similar issue and I fixed it by adding similar code as @maurymmarques 

```
$(document).on('page:change', function(){
    initWiceGrid(); 
});
```

**Comment by kreintjes** [comment]
The CSV download problem is fixed in https://github.com/leikind/wice_grid/pull/342
