### ISSUE TITLE
jQuery + :negation_in_filter always submits =1, regardless of checkbox.checked

### ISSUE THREAD

**Issue by iva2k** [leikind/wice_grid#32]
I traced to code in generators/wice_grid_jquery.js:read_values_and_form_query_string function, where line
    res.push(templates[i]  + encodeURIComponent(val));
is called for a checkbox, regardless of its "checked" state. According to HTML spec, checkboxes always have value set, and the submit only posts value when the checkbox is checked. Therefore, the code should not run if the control is a checkbox and it is is not checked.

**Comment by leikind** [comment]
fixed: http://github.com/leikind/wice_grid/commit/933e5725d5dca6ce760b95f250c4cdcc5d1c129c
Thanks!
