### ISSUE TITLE
using current_page_records and all_pages_records from controller (e.g. for XML format)

### ISSUE THREAD

**Issue by iva2k** [leikind/wice_grid#33]
I am trying to make XML export for index action. Trying this pattern:

```
  def index
    @objects_grid = initialize_grid(Users)
    unless export_grid_if_requested
      respond_to do |format|
        format.html
        format.xml  { render :xml => @objects_grid.current_page_records }
      end
    end
  end
```

It does not work (as explained nicely in README/Accessing Records Via The WiceGrid Object). I think it is very good use case though. It will allow any export format without a need to mess with wice_grid internals. It would be acceptable to require a partial with grid to return records properly, something like this:

```
  def index
    @objects_grid = initialize_grid(Users)
    unless export_grid_if_requested
      respond_to do |format|
        format.html
        format.xml  { render :xml => @objects_grid.current_page_records(:partial => 'users_grid') }
      end
    end
  end
```

Any recommendations?

**Comment by leikind** [comment]
This can only be done by changing the architecture of the plugin, because until the view helper is evaluated, with all its column definitions, the final SQL request to retrieve records for the current page cannot be built

**Comment by iva2k** [comment]
Yuri, Thanks for fixing the other bugs so promptly! 

I understand your concern with changing plugin architecture. I did not mean to suggest changing the architecture, instead I wanted to find a way to work with existing architecture and support getting the records out. This will utilize wonderful filters functionality and allow plugin users to extend export functionality. I played around, and this code does what I want it to:

```
def index
  @objects_grid = initialize_grid(Users)
  unless export_grid_if_requested
    respond_to do |format|
      format.html
      format.xml  {
        p = 'users_grid'
        s = render_to_string :template => 'users/_' + p + '.html'
        render :xml => @objects_grid.current_page_records
      }
    end
  end
end
```

It works, however, I do not like the ugly "s=render_to_string..." code at all. It would be better to have "@objects_grid.current_page_records" take an optional name of the partial (p), do the "s=..." call behind the scenes, and return the records. I stumbled at trying to do so... render and render_to_string are protected ActionController methods, so I cannot call them from WiceGrid. 

Any ideas? I made it work by passing a block/lambda, but it is not more elegant than the "s=..." above. 

One more thing would be possible to do next if grid.current_page_records took care of the partial is to optimize the performance by not creating the whole HTML string "s" that is not used anyway, just go over the column definitions in the partial. That would be a trivial step once the protected methods are resolved.

**Comment by leikind** [comment]
Well, I can suggest obj.send(:a_protected_method), but this is not a lot more beautiful than a lambda.

You idea of running the view from current_page_records is interesting, though frankly speaking  this leads the API a bit to the dark side of the force :) 
Let me play with this idea.

Theoretically, why should column definition be in the view? 
Would be great if column could be defined in the controller, and their content (the blocks) - in the view.  Could be the next rewrite. Though this way it gets a bit heavy...

I cannot devote a lot of time to the plugin at the moment, so if you experiment with the plugin and modify the source code, feel free to fork it on Github and publish your changes, if you wish.

**Comment by iva2k** [comment]
> Theoretically, why should column definition be in the view?
> Would be great if column could be defined in the controller, and their content (the blocks) - in the view. 

I totally with you on that. Given that the plugin builds up on top of the model, all you need by the time you do View > grid, is a good description of columns, and how to display them. Column descriptions can come from either controller, view, or model introspection. Display description can also come from the controller(optional), or from the view, or defaults can be derived automagically. If controller does not define any columns in initialize_grid, last place is view (like it is done now). 

I also agree it is not in the scope of the issue at hand, so back to the XML export... 

A better organized code that works, and it makes a little bit more sense:

```
# wice_grid_controller.rb:
def grid_current_page_records(opts = {})
  grid = opts[:grid] || self.wice_grid_instances.detect(&:output_html?)
  if grid
    template_name = opts[:template]
    template_name ||= opts[grid.name] || opts[grid.name.intern]
    template_name ||= grid.name + '_grid'
    temp_html = render_to_string(:partial => template_name + '.html')
    grid.current_page_records
  end
end

# controllers/user_controller.rb:

def index
  @objects_grid = initialize_grid(User)
  unless export_grid_if_requested
    respond_to do |format|
      format.html
      format.xml  {
        render :xml => grid_current_page_records(:grid => @objects_grid, :template => 'users_grid')
      }
    end
  end
end
```

I still don't like "+'.html'", but that is the nature of this hack.
For optimization, temp_html can be made empty by means of new property grid.@dry_run=true which will disable html builder section of the view:grid.

**Comment by tomkurt** [comment]
I want different columns for the export function.

``` ruby

export_xls([:name, :description, :price ]) # place this in app/views/products/index.html.csv

 def export_xls columns
    # hack to trigger search
    grid(@grid) do |row|
      columns.each do |column|
        row.column column
      end
    end
    ([CSV.generate_line(columns.map{|column| I18n.t(column) }, "\t")] +
    @grid.resultset.map do |object|
      CSV.generate_line(columns.map do |column|
        ignore_nil{ object.instance_eval(column.to_s) }
      end, "\t")
    end).join("\n") 
  end
```

**Comment by leikind** [comment]
why are you posting this under this ticket?

I fail to get the point of this code chunk, but if you want to have different columns in html and csv, use  options :in_csv and :in_html as described in section CSV Export of the readme (https://github.com/leikind/wice_grid)

**Comment by leikind** [comment]
Please let me know if I've understood your request correctly

**Comment by tomkurt** [comment]
Thank you very much leikind. That is what I needed.
I did not read the docs that well, sorry.
