### ISSUE TITLE
Showing all records doesn't behave properly when the filter is updated

### ISSUE THREAD

**Issue by xavier** [leikind/wice_grid#35]
How to reproduce:
1. Filter on some criterion (let N be the total number of records in the result set)
2. Toggle "show all records"
3. Change the filter so you get a total number of records which is greater than N

At that point, the grid shows only N records and displays _both_ "show all" and "back to paginated view" links.

I guess that a more appropriate behavior would be either to :
- reset the display mode to paginated view when the filter is updated; or
- stick with "show all" but then actually show all records from the new results set.

**Comment by leikind** [comment]
I prefer the second option.  Checkout the fix - http://github.com/leikind/wice_grid/commit/7c6020ff066e253179ad64773a3a8f9aff862d86
