### ISSUE TITLE
Rails 5 Compatibility [Answered]

### ISSUE THREAD

**Issue by patricklindsay** [leikind/wice_grid#353]
Hey guys,

I've gone ahead and [created a fork](https://github.com/patricklindsay/wice_grid) which is Rails 5+ compatible. Support for anything less than 5 has been dropped in the fork.

## Usage
```
# Rails => 5
gem 'wice_grid', git: 'https://github.com/patricklindsay/wice_grid.git', tag: 'v4.0.0'

# Rails < 5
gem 'wice_grid', '3.6.2'
```

I've tagged it in GitHub as `v4.0.0` so that people can point to the tag rather than pointing at a raw branch (scary).

Thanks Yuri for the great work. Hopefully this will mean a few less annoying notifications for you :)

**Comment by leikind** [comment]
👍

**Comment by leikind** [comment]
Would you like a link to the fork in the README so that everyone sees it?

**Comment by patricklindsay** [comment]
Yah good idea.

**Comment by Vinnie1991** [comment]
Thanks for the great gem!

But could you please transfer the Rubygems entry to @patricklindsay?

**Comment by leikind** [comment]
@Vinnie1991 it was done already some time ago, please look here https://rubygems.org/gems/wice_grid

**Comment by Vinnie1991** [comment]
Sorry didn't see it! Thanks.

**Comment by patricklindsay** [comment]
Quick update on this - 

`4.1.0` released (Rails 5+ compatible) and available through ruby gems. Thanks Yuri!

I'll leave this open for anyone who still ends up here.

**Comment by guillenjs** [comment]
I know this is an older issue but I was wondering if `4.1.0 ` release is compatible with rails 6+

I noticed in the ruby gem documentation that it states `rails < 5.3, ~> 5.0` as dependency

**Comment by patricklindsay** [comment]
Rails 6 isn't yet supported. I no longer use WiceGrid so have no plan to work on this however others are running on modified versions of WiceGrid using Rails 6 - I'll happily merge a PR which provides Rails 6 support and has been tested by multiple parties - https://github.com/patricklindsay/wice_grid/issues/74
