### ISSUE TITLE
Integer column copywriter feature

### ISSUE THREAD

**Issue by bypang1226** [leikind/wice_grid#38]
Hello Yuri,

I found most users just want to search the exact value instead a range search of an Integer.

So I hacked into the ViewColumnInteger class in view_column.rb, and make a simple javascript addon to line 196

opts1 = {:size => 3, :id => @dom_id, :onkeyup=>"$(#{@dom_id2}).value=$(this).value"}

This will enlighten user experience a bit without losing usefulness of range search abilty.

**Comment by leikind** [comment]
Added in 3.0.0pre3 (Rails 3) and 0.6.2 (Rails 2). Off by default. See Wice::Defaults::SECOND_RANGE_VALUE_FOLLOWING_THE_FIRST in the config
