### ISSUE TITLE
NameError (uninitialized constant Wice::Defaults::JS_FRAMEWORK)

### ISSUE THREAD

**Issue by sunnyboy** [leikind/wice_grid#39]
The title explains the problem :-)
Everything seems to be properly installed with one only problem.
That 's the message Message : JS_FRAMEWORK constant is not initialized.
Which causes logically crash of the Application.

Environmet:
Rails 3.0.3
ruby 1.9.2p174
running RVM
installed Gems:
gem 'rails'
gem 'mysql2'
gem 'heroku'
gem 'will_paginate'
gem 'dropbox'
gem 'nifty-generators'
gem 'simple_form'
gem 'jquery-rails'
gem 'wice_grid', '3.0.0.pre1'

Maybe it has got some influence- I get always by starting the Server also the Warning:
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:65: warning: already initialized constant State
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:66: warning: already initialized constant SAFE_STATE_PROTOTYPE
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:67: warning: already initialized constant FAST_STATE_PROTOTYPE
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:74: warning: already initialized constant PRETTY_STATE_PROTOTYPE/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/ext.rb:14: warning: already initialized constant JSON_LOADED 

...but this warning is not causing the crash of the applicayion. Only sucks.

thanks for any great idea.

nstant JSON_LOADED

**Comment by leikind** [comment]
Hello,

What happens if you run the following command in the root of your Rail app:

   cat config/initializers/wice_grid_config.rb

**Comment by sunnyboy** [comment]
The result is:
cat: config/initializers/wice_grid_cig.rb: No such file or directory

**Comment by sunnyboy** [comment]
It 's getting worse....
Now when I tried again: 
rails g wice_grid_assets_jquery

I get message: Could not find generator wice_grid_assets_jquery.

can this behavior have some ligical explanation?

thank you very much for any help or idea.
Michael

**Comment by leikind** [comment]
As I understood, you haven't run the generator yet. Then the first error is because you don't have wice_grid_config.rb in config/initializers.

Now, why you can't run the generator task is another problem. 

Please post your Gemfile here, and the output of the command  

   rails g

**Comment by leikind** [comment]
Plus the full stacktrace of the exception which crashes your app

**Comment by sunnyboy** [comment]
thanks for your patient help...
so the command gives (as could be expected):
cat: config/initializers/wice_grid_config.rb: No such file or directory

Seems that wice_grid_config.rb is not in config/initializers :-(

This is the Gemfile:
http://dl.dropbox.com/u/1143421/MailAttachments/Gemfile

and rails g is sayng:
/Users/sopira/rubydev/simple_cms/config/initializers/simple_form.rb:2:in `<top (required)>': uninitialized constant SimpleForm (NameError)
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/engine.rb:201:in`block (2 levels) in class:Engine'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/engine.rb:200:in `each'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/engine.rb:200:in`block in class:Engine'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/initializable.rb:25:in `instance_exec'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/initializable.rb:25:in`run'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/initializable.rb:49:in`each'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/initializable.rb:49:in `run_initializers'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/application.rb:134:in`initialize!'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
    from /Users/sopira/rubydev/simple_cms/config/environment.rb:5:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/application.rb:103:in `require_environment!'
    from /Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.3/lib/rails/commands.rb:16:in`<top (required)>'
    from internal:lib/rubygems/custom_require:33:in `require'
    from <internal:lib/rubygems/custom_require>:33:in`rescue in require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from script/rails:6:in`<main>'

**Comment by sunnyboy** [comment]
Full trace:
wice_grid (3.0.0.pre1) lib/js_adaptors/js_adaptor.rb:6:in `init'
wice_grid (3.0.0.pre1) lib/wice_grid_controller.rb:69:in`initialize_grid'
app/controllers/stories_controller.rb:14:in `list'
app/controllers/stories_controller.rb:10:in`index'
actionpack (3.0.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.0.3) lib/abstract_controller/base.rb:151:in`process_action'
actionpack (3.0.3) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.3) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (3.0.3) lib/active_support/callbacks.rb:445:in `_run__520630581660084238__process_action__599384815975661123__callbacks'
activesupport (3.0.3) lib/active_support/callbacks.rb:409:in`_run_process_action_callbacks'
activesupport (3.0.3) lib/active_support/callbacks.rb:93:in `run_callbacks'
actionpack (3.0.3) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in`block in instrument'
activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in`instrument'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.0.3) lib/action_controller/metal/rescue.rb:17:in`process_action'
actionpack (3.0.3) lib/abstract_controller/base.rb:120:in `process'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:40:in`process'
actionpack (3.0.3) lib/action_controller/metal.rb:138:in `dispatch'
actionpack (3.0.3) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.0.3) lib/action_controller/metal.rb:178:in `block in action'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in`call'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:27:in`call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in `block in call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in`block in recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:68:in `optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in`recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:492:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/head.rb:14:in`call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/cookies.rb:295:in `call'
activerecord (3.0.3) lib/active_record/query_cache.rb:32:in`block in call'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.3) lib/active_record/query_cache.rb:12:in`cache'
activerecord (3.0.3) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
activesupport (3.0.3) lib/active_support/callbacks.rb:415:in`_run_call_callbacks'
actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.1) lib/rack/sendfile.rb:107:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/show_exceptions.rb:46:in`call'
railties (3.0.3) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.1) lib/rack/runtime.rb:17:in`call'
activesupport (3.0.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in`block in call'
internal:prelude:10:in `synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.3) lib/rails/application.rb:168:in`call'
railties (3.0.3) lib/rails/application.rb:77:in `method_missing'
railties (3.0.3) lib/rails/rack/log_tailer.rb:14:in`call'
rack (1.2.1) lib/rack/content_length.rb:13:in `call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in`service'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'

**Comment by leikind** [comment]
Well, first of all, there is already version 3.0.0.pre2 out there, so change the version and run the bundle command. 

Second, your application is not startable because of some missing constant SimpleForm, and that has nothing to do with WiceGrid.

Upgrade the wice_grid gem, solve your SimpleForm problem, and try to run 'rails g' again.

**Comment by sunnyboy** [comment]
When I remove gem 'wice_grid', '3.0.0.pre1' and respective code from the App, it runs again normally...

And I would like so much to run wice_grid.
As seen on the example site- it rocks, it's huge.

**Comment by leikind** [comment]
Please upgrade the gem to pre2

**Comment by leikind** [comment]
it can be faster via jabber or google talk, you can try to send a message to yuri.leikind [at] gmail.com

**Comment by sunnyboy** [comment]
Updated to gem pre2
Simple Form commented out
Rails g is giving folloving output:
Michael-Sopiras-iMac27:simple_cms sopira$ rails g
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:65: warning: already initialized constant State
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:66: warning: already initialized constant SAFE_STATE_PROTOTYPE
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:67: warning: already initialized constant FAST_STATE_PROTOTYPE
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/common.rb:74: warning: already initialized constant PRETTY_STATE_PROTOTYPE
/Users/sopira/.rvm/gems/ruby-1.9.2-head@rails3/gems/json_pure-1.4.6/lib/json/ext.rb:14: warning: already initialized constant JSON_LOADED
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  controller
  generator
  helper
  integration_test
  mailer
  migration
  model
  observer
  performance_test
  plugin
  resource
  scaffold
  scaffold_controller
  session_migration
  stylesheets

Jquery:
  jquery:install

Nifty:
  nifty:authentication
  nifty:config
  nifty:layout
  nifty:scaffold

WiceGrid:
  wice_grid:wice_grid_assets_jquery
  wice_grid:wice_grid_assets_prototype

and full trace is (applications crashes):

wice_grid (3.0.0.pre2) lib/helpers/wice_grid_view_helpers.rb:113:in `grid'
app/views/stories/_index_table.html.erb:49:in`_app_views_stories__index_table_html_erb___2868730198579256851_2170124680__1097313210420629911'
actionpack (3.0.3) lib/action_view/template.rb:135:in `block in render'
activesupport (3.0.3) lib/active_support/notifications.rb:54:in`instrument'
actionpack (3.0.3) lib/action_view/template.rb:127:in `render'
actionpack (3.0.3) lib/action_view/render/partials.rb:333:in`render_partial'
actionpack (3.0.3) lib/action_view/render/partials.rb:262:in `block in render'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in`block in instrument'
activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in`instrument'
actionpack (3.0.3) lib/action_view/render/partials.rb:260:in `render'
actionpack (3.0.3) lib/action_view/render/partials.rb:378:in`_render_partial'
actionpack (3.0.3) lib/action_view/render/rendering.rb:22:in `render'
app/views/stories/list.html.erb:14:in`_app_views_stories_list_html_erb___2684887876496211043_2171467120__1464502924662802197'
actionpack (3.0.3) lib/action_view/template.rb:135:in `block in render'
activesupport (3.0.3) lib/active_support/notifications.rb:54:in`instrument'
actionpack (3.0.3) lib/action_view/template.rb:127:in `render'
actionpack (3.0.3) lib/action_view/render/rendering.rb:59:in`block in _render_template'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.3) lib/action_view/render/rendering.rb:56:in`_render_template'
actionpack (3.0.3) lib/action_view/render/rendering.rb:26:in `render'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:114:in`_render_template'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:108:in `render_to_body'
actionpack (3.0.3) lib/action_controller/metal/renderers.rb:47:in`render_to_body'
actionpack (3.0.3) lib/action_controller/metal/compatibility.rb:55:in `render_to_body'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:101:in`render_to_string'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:92:in `render'
actionpack (3.0.3) lib/action_controller/metal/rendering.rb:17:in`render'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.0.3) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/benchmark.rb:309:in `realtime'
activesupport (3.0.3) lib/active_support/core_ext/benchmark.rb:5:in`ms'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:78:in`cleanup_view_runtime'
activerecord (3.0.3) lib/active_record/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:39:in`render'
app/controllers/stories_controller.rb:11:in `index'
actionpack (3.0.3) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (3.0.3) lib/abstract_controller/base.rb:151:in `process_action'
actionpack (3.0.3) lib/action_controller/metal/rendering.rb:11:in`process_action'
actionpack (3.0.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.0.3) lib/active_support/callbacks.rb:445:in`_run__854652909640658603__process_action__2641253058890605289__callbacks'
activesupport (3.0.3) lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
activesupport (3.0.3) lib/active_support/callbacks.rb:93:in`run_callbacks'
actionpack (3.0.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
activesupport (3.0.3) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.0.3) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.0.3) lib/abstract_controller/base.rb:120:in`process'
actionpack (3.0.3) lib/abstract_controller/rendering.rb:40:in `process'
actionpack (3.0.3) lib/action_controller/metal.rb:138:in`dispatch'
actionpack (3.0.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.0.3) lib/action_controller/metal.rb:178:in`block in action'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in `call'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in`dispatch'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:27:in `call'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in`block in call'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in `block in recognize'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:68:in`optimized_each'
rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in `recognize'
rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in`call'
actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:492:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/head.rb:14:in `call'
rack (1.2.1) lib/rack/methodoverride.rb:24:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/flash.rb:182:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/cookies.rb:295:in`call'
activerecord (3.0.3) lib/active_record/query_cache.rb:32:in `block in call'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
activerecord (3.0.3) lib/active_record/query_cache.rb:12:in `cache'
activerecord (3.0.3) lib/active_record/query_cache.rb:31:in`call'
activerecord (3.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:46:in`block in call'
activesupport (3.0.3) lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:44:in`call'
rack (1.2.1) lib/rack/sendfile.rb:107:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
actionpack (3.0.3) lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
railties (3.0.3) lib/rails/rack/logger.rb:13:in`call'
rack (1.2.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.0.3) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
rack (1.2.1) lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in`synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/static.rb:30:in`call'
railties (3.0.3) lib/rails/application.rb:168:in `call'
railties (3.0.3) lib/rails/application.rb:77:in`method_missing'
railties (3.0.3) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in`call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/Users/sopira/.rvm/rubies/ruby-1.9.2-head/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

**Comment by leikind** [comment]
Ok, now at least your generator command does not fail (only gives a bunch of warnings), so you can try to run the wice_grid generator:

```
rails  g  wice_grid:wice_grid_assets_jquery 
```

**Comment by sunnyboy** [comment]
ehm... the problem was out of you great wice_grid ...
now it's running like a charm.
thank you very much for your time and GREAT support.

**Comment by leikind** [comment]
Ok, no problem, you are welcome. Enjoy. Submit more bug reports :)

**Comment by sunnyboy** [comment]
Now when I can really use wice_grid, the bugs will be reported.
Even I hope not to experience too much of them.
Michael
