### ISSUE TITLE
Rails 7.2 - PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type integer

### ISSUE THREAD

**Issue by afdev82** [leikind/wice_grid#395]
## Description of issue
When I try to filter the data on the ID column (integer), I have the following error:

>     PG::InvalidTextRepresentation: ERROR: invalid input syntax for type integer: "65578.0"

## Expected behaviour
The data are filtered by ID and the results contain only one record.

## Environment

- Ruby **3.3.5**
- Rails **7.2.1.1**
- WiceGrid **7.1.2**

## Additional context
With Rails 7.1.4.1 it works.
With WiceGrid v7.1.1, I didn't have the error, but the results were not filtered for that column. I had all rows and not only one.

I am trying to debug myself, but any help would be much appreciated.
Thank you for your support.

**Comment by afdev82** [comment]
Probably I have identified [the method that throw](https://github.com/leikind/wice_grid/blob/rails7/lib/wice/helpers/wice_grid_view_helpers.rb#L121C45-L121C64)s the error.
In my logs I have:

```
(byebug) grid.resultset.size
  SQL (0.9ms)  SELECT DISTINCT "configurations"."configuration_id" AS alias_0, "configurations"."configurations"."configuration_id" FROM "configurations"."configurations" LEFT OUTER JOIN "alchemy_sites" ON "alchemy_sites"."id" = "configurations"."configurations"."website_id" LEFT OUTER JOIN "system"."countries" ON "system"."countries"."country_id" = "configurations"."configurations"."country_id" LEFT OUTER JOIN "configurations"."custom_models" ON "configurations"."custom_models"."custom_model_id" = "configurations"."configurations"."custom_model_id" LEFT OUTER JOIN "system"."users" ON "system"."users"."user_id" = "configurations"."configurations"."user_id" LEFT OUTER JOIN "configurations"."prices" ON "configurations"."prices"."configuration_id" = "configurations"."configurations"."configuration_id" WHERE (("configurations"."configurations"."is_preset" = TRUE AND "configurations"."configurations"."measurement_system" = 'metric' AND "configurations"."configurations"."deleted_at" IS NULL) OR (("configurations"."configurations"."website_id" IN (7, 10, 11, 1, 4, 12, 5, 8, 2, 9, 3, 6) AND "configurations"."configurations"."deleted_at" IS NULL) OR ("configurations"."configurations"."user_id" = 1 AND "configurations"."configurations"."website_id" = 1 AND "configurations"."configurations"."deleted_at" IS NULL))) AND "configurations"."configurations"."archived_at" IS NULL AND "configurations"."configurations"."configurable" = $1 AND ( configurations.configurations.configuration_id = $2 ) ORDER BY "configurations"."configuration_id" DESC LIMIT $3 OFFSET $4  [["configurable", true], [nil, 65578.0], ["LIMIT", 20], ["OFFSET", 0]]
  ↳ (byebug):1:in `define_grid'
*** ActiveRecord::StatementInvalid Exception: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type integer: "65578.0"
```

Now I am inspecting where the params are processed to build the query, I think [here](https://github.com/leikind/wice_grid/blob/rails7/lib/wice_grid.rb#L284).
The ID I send in the request obviously has no decimal point.

**Comment by dima4p** [comment]
Fixed in https://github.com/leikind/wice_grid/commit/a974053c1a9c48496a0ac49610c6f9fbb49b3b03

**Comment by afdev82** [comment]
Thank you.
