### ISSUE TITLE
Rails7.1 - ArgumentError (missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`.)

### ISSUE THREAD

**Issue by lx-nihei** [leikind/wice_grid#399]
## Description of issue
When using WiceGrid in a Rails 7.1 or higher environment, an `ArgumentError` occurs with the following message: 
```
Started GET "/" for ::1 at 2024-11-07 11:56:54 +0900
  ActiveRecord::SchemaMigration Load (0.0ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC

ArgumentError (missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`.):

activerecord (7.1.5) lib/active_record/attribute_methods/serialization.rb:208:in `serialize'
wice_grid (7.1.4) lib/wice/wice_grid_serialized_query.rb:2:in `<class:WiceGridSerializedQuery>'
wice_grid (7.1.4) lib/wice/wice_grid_serialized_query.rb:1:in `<main>'
/Users/ysh-nh/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
/Users/ysh-nh/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
bootsnap (1.18.4) lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
zeitwerk (2.7.1) lib/zeitwerk/core_ext/kernel.rb:34:in `require'
wice_grid (7.1.4) lib/wice_grid.rb:40:in `on_action_view_load'
wice_grid (7.1.4) lib/wice_grid.rb:58:in `block (2 levels) in <class:WiceGridEngine>'
```

This issue is expected to be caused by the following Rails PR, which changes the default value of `config.active_record.default_column_serializer`.
https://github.com/rails/rails/pull/47422

## Expected behavior
Grid function works without error.

## Actual behavior
Grid function causes error.

## Steps to reproduce
1. Create a Rails app with Rails 7.1 or higher.
2. Add `wice_grid` gem to the Gemfile and run `bundle install`.
3. Start the Rails server
4. Access any page and observe the error.

ArgumentError occurs only on first access after server startup.
In the second and subsequent accesses, ArgumentError does not occur but css is not applied.

## Environment
- Ruby **3.3.0**
- Rails **7.1.5**
- WiceGrid **7.1.4**

**Comment by dima4p** [comment]
Add to your `application.rb` the line
`config.active_record.default_column_serializer = YAML`
