### ISSUE TITLE
Add filter to virtual column

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#42]
Hi!
I have a virtual column: STATUS that comes from a few terms. I plan to use Detach_with_id.
How can I do this without having to create a new column?

PS.: I stated in the model attr_accessor :status but still have problems.

Browser this message:
WiceGrid: Column 'status' is not found in table 'transacoes'! If 'status' belongs to another table you should declare it in :include or :join when initialising the grid, and specify :model_class in column declaration.

**Comment by leikind** [comment]
Don't declare :attribute_name.  :attribute_name is the name of a db table column, the plugin expects to find it in the DB. Also, without :attribute_name there will be no filter (no database column - no filter)

**Comment by fillipenorton** [comment]
Ok.

I'll try another way!

Thank you!
