### ISSUE TITLE
Filter Default

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#44]
Hi!
I would like to bring a filter default. E.g.: Show at the index only the records of current month. What better way ?
I tried a few things in the controller but I had no success.

Thanks a lot

**Comment by leikind** [comment]
If I understand the task correctly, maybe wice_grid_custom_filter_params can help: http://leikind.org/apis/wice_grid/classes/Wice/Controller.html#M000014  and the example here http://grid.leikind.org/custom_filter_params (click on the links i the table). wice_grid_custom_filter_params  generates a request fragment in the format WiceGrid understands.
Anyway, if it's not what you need, it's just a matter of putting the right parameters into params, you can manually set the state of the grid and analyze params and the url.
