### ISSUE TITLE
Wice::define_routes(map, controller) in Routes.rb not working

### ISSUE THREAD

**Issue by atif** [leikind/wice_grid#46]
The define_routes method expects a IActionController::Routing::RouteSet::Mapper object, and controller. name. In rails 3, the ActionController::Routing::RouteSet::Mapper has been deprecated. I'm gettng the exception:

undefined method `create_serialized_query_url' for Class

Seems the routes are not picked by the Rails 3 environment. What change is required to make it work?

Thanks

**Comment by leikind** [comment]
It looks like you are trying to use WiceGrid for Rails 2 in Rails 3.

Here is a define_routes in version 0.6.2 : https://github.com/leikind/wice_grid/blob/master/lib/wice_grid_serialized_queries_controller.rb#L9

and here it is in 3.0.0.pre3 https://github.com/leikind/wice_grid/blob/rails3/lib/wice_grid_serialized_queries_controller.rb#L9

Here it is in action in a Rails 3 app: https://github.com/leikind/wice_grid_examples/blob/rails3_jquery/config/routes.rb#L51
