### ISSUE TITLE
Deleting selected records

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#49]
Hi!

I'm trying to delete multiple records. Added the g.action_column but can not create the button to send the parameters of the selected records to the controller. Can you help me? Give some idea of how to do?

Thanks so much

Fillipe Norton

**Comment by leikind** [comment]
Hi,

Please take a look at this example: http://grid.leikind.org/action_column , click on View code

Yuri

**Comment by fillipenorton** [comment]
Ok! Thank you, one more time!
