### ISSUE TITLE
Not working with jQuery

### ISSUE THREAD

**Issue by uu** [leikind/wice_grid#5]
If you replace prototype with jRails, wice_grid will fail to load.

**Comment by masterkain** [comment]
jrails maps common rails' js helpers to use jquery and other minor stuff, but wice_grid also writes custom JS, thus rendering it prototype dependant.
I agree though would be nice to see a jquery version of wice_grid but I think it will be much work; maybe one day I'll fork the project and make the switch, but I don't have time right now :)

**Comment by leikind** [comment]
Actually it's not that much work, there's  not so much javascript. jQuery support is planned.

**Comment by leikind** [comment]
Branch http://github.com/leikind/wice_grid/tree/jquery_and_prototype supports both jQuery and Prototype. The only thing missing is a calendar widget for jQuery.

**Comment by leikind** [comment]
closing
