### ISSUE TITLE
csv export not working in production environment

### ISSUE THREAD

**Issue by troessner** [leikind/wice_grid#50]
**Used versions:**

$ bundle list rails
/home/timo/.rvm/gems/ruby-1.8.7-p334@lempack/gems/rails-3.0.3

$ bundle list wice_grid
/home/timo/.rvm/gems/ruby-1.8.7-p334@lempack/gems/wice_grid-3.0.0.pre3

**Symptoms:**

In development mode csv export works like a charm:

  rails s
  ...........
  Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Wed May 04 16:52:58 +0200 2011
  Processing by Admin::OrdersController#index as HTML
  Parameters: {"orders"=>{"export"=>"csv"}}
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 8) LIMIT 1
  Role Load (0.1ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id   WHERE ((`assignments`.user_id = 8))
  Order Load (0.1ms)  SELECT `orders`.\* FROM `orders` ORDER BY `orders`.`magento_id` asc
Rendered admin/orders/_orders_grid.html.haml (85.9ms)
Sent file /tmp/orders20110504-15409-u88tk4-0 (0.1ms)
Completed 200 OK in 225ms

-> That's ok, the csv looks good.

Unfortunately the very same request doesnt work in production:

rails s -e production
...................
Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Wed May 04 16:56:17 +0200 2011
  Processing by Admin::OrdersController#index as HTML
  Parameters: {"orders"=>{"export"=>"csv"}}
Rendered admin/orders/_orders_grid.html.haml (101.6ms)
Sent file /tmp/orders20110504-15877-467q6z-0 (0.1ms)
Completed 200 OK in 105ms

The csv file gets send back, but it's empty. Note that the csv export doesn't work for any of my models in production (all of which are standard AR models).

**The problem is apparently that this query isnt executed (among others):**

_Order Load (0.1ms) SELECT orders._ FROM orders ORDER BY orders.magento_id asc*

Seems like an issue with query caching - but this doesn't make sense since the csv export is triggered by a totally separate request (and actually I can see in the logs that this query hasn't been executed ever).

Anything obvious I am missing here?

**Comment by leikind** [comment]
Interesting.

Could you please set the log level of both development and production to :debug  (add line 'config.log_level = :debug' to config/environments/production.rb and  config/environments/development.rb), re-run the request and post the logs here again?

Also, could you turn on class caching _in development_ temporarily to true (config.cache_classes = true ) and see if it breaks the csv export in development?

**Comment by troessner** [comment]
_Also, could you turn on class caching in development temporarily to true (config.cache_classes = true ) and see if it breaks the csv export in development?_

No, that does **not** break the csv export.

_Could you please set the log level of both development and production to :debug (add line 'config.log_level = :debug' to config/environments/production.rb and config/environments/development.rb), re-run the request and post the logs here again?_

Hmmm, setting the log level to debug does show something interesting:

**In development:**

Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Wed May 04 17:51:48 +0200 2011
  Processing by Admin::OrdersController#index as HTML
  Parameters: {"orders"=>{"export"=>"csv"}}
  User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 8) LIMIT 1
  Role Load (0.1ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id WHERE ((`assignments`.user_id = 8))
  Order Load (0.2ms)  SELECT `orders`.\* FROM `orders` ORDER BY `orders`.`magento_id` asc
Rendered admin/orders/_orders_grid.html.haml (101.2ms)
Sent file /tmp/orders20110504-25279-bb5a8j-0 (0.1ms)
Completed 200 OK in 105ms

**In production:**

Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Wed May 04 17:55:35 +0200 2011
  Processing by Admin::OrdersController#index as HTML
  Parameters: {"orders"=>{"export"=>"csv"}}
  User Load (0.2ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 8) LIMIT 1
  Role Load (0.1ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id WHERE ((`assignments`.user_id = 8))
  Order Load (0.2ms)  SELECT `orders`.\* FROM `orders` ORDER BY `orders`.`magento_id` asc
Rendered admin/orders/_orders_grid.html.haml (100.2ms)
Sent file /tmp/orders20110504-26117-1wxe5l5-0 (0.1ms)
Completed 200 OK in 105ms

**I diff'ed the two outputs and they are identical** (ignoring obvious differences like time stamps etc.)

Alright, so at least we know that this is not the problem.

**Comment by leikind** [comment]
Could you please open the gem in your editor (bundle open wice_grid), open file wice_grid.rb, line 284:

```
          @resultset = self.output_csv? ?  @klass.find(:all, @ar_options) : @klass.paginate(@ar_options)
```

 And try to insert some logging message with the number of records in resultset (make sure the method still returns this 
value :)   )

Let's compare the number of records for the csv output

**Comment by troessner** [comment]
I debugged it like that:

```
with_exclusive_scope do
   @resultset = self.output_csv? ?  @klass.find(:all, @ar_options) : @klass.paginate(@ar_options)
   custom_log "resultset size is #{@resultset.count}"
end
```

In BOTH cases (development and production) the output is:

"resultset size is 77"

However the downloaded file in production mode is still empty (really physically empty, i double checked that).

**Comment by leikind** [comment]
What is the value of Wice::Defaults::ERB_MODE in config/initializers/wice_grid_config.rb?

**Comment by leikind** [comment]
Could you please open wice_grid_controller.rb , and replace method export_grid_if_requested by this version with log messages:

```
def export_grid_if_requested(opts = {})
  grid = self.wice_grid_instances.detect(&:output_csv?)

  if grid
    template_name = opts[grid.name] || opts[grid.name.intern]
    template_name ||= grid.name + '_grid'
    temp_filename = render_to_string(:partial => template_name)
    logger.debug("WG) temp_filename 1: #{temp_filename}")
    temp_filename.strip!
    logger.debug("WG) temp_filename 2: #{temp_filename}")
    filename = (grid.csv_file_name || grid.name ) + '.csv'
    logger.debug('WG) wc 1: ' + `wc #{temp_filename}`)
    grid.csv_tempfile.close
    logger.debug('WG) wc 2 ' + `wc #{temp_filename}`)
    send_file temp_filename, :filename => filename, :type => 'text/csv'
    grid.csv_tempfile = nil
    true
  else
    yield if block_given?
    false
  end
end
```

and send me the generated log messages?

**Comment by troessner** [comment]
_What is the value of Wice::Defaults::ERB_MODE in config/initializers/wice_grid_config.rb?_

```
Wice::Defaults::ERB_MODE = false
```

_Could you please open wice_grid_controller.rb , and replace method export_grid_if_requested by this version with log messages:_

Since it isn't _that_ much output I'd prefer to keep it here to prevent jumping back and forth.

**In development:**

Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Thu May 05 13:13:25 +0200 2011
      Processing by Admin::OrdersController#index as HTML
      Parameters: {"orders"=>{"export"=>"csv"}}
      SQL (0.5ms)  SHOW TABLES
      User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 8) LIMIT 1
      Role Load (0.1ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id WHERE ((`assignments`.user_id = 8))
      Order Load (0.2ms)  SELECT `orders`.\* FROM `orders` ORDER BY `orders`.`magento_id` asc
    Rendered admin/orders/_orders_grid.html.haml (96.3ms)
    WG) temp_filename 1: /tmp/orders20110505-4910-3h0mho-0
    WG) temp_filename 2: /tmp/orders20110505-4910-3h0mho-0
    WG) wc 1:  110  112 4096 /tmp/orders20110505-4910-3h0mho-0
    WG) wc 2  151  153 5710 /tmp/orders20110505-4910-3h0mho-0
    Sent file /tmp/orders20110505-4910-3h0mho-0 (0.2ms)
    Completed 200 OK in 169ms

**In production:**

Started GET "/admin/orders?orders[export]=csv" for 127.0.0.1 at Thu May 05 13:11:14 +0200 2011
      Processing by Admin::OrdersController#index as HTML
      Parameters: {"orders"=>{"export"=>"csv"}}
      User Load (0.1ms)  SELECT `users`.\* FROM `users` WHERE (`users`.`id` = 8) LIMIT 1
      Role Load (0.1ms)  SELECT `roles`.\* FROM `roles` INNER JOIN `assignments` ON `roles`.id = `assignments`.role_id WHERE ((`assignments`.user_id = 8))
      Order Load (0.2ms)  SELECT `orders`.\* FROM `orders` ORDER BY `orders`.`magento_id` asc
    Rendered admin/orders/_orders_grid.html.haml (113.9ms)
    WG) temp_filename 1: /tmp/orders20110505-4469-1qw7fan-0
    WG) temp_filename 2: /tmp/orders20110505-4469-1qw7fan-0
    WG) wc 1:  110  112 4096 /tmp/orders20110505-4469-1qw7fan-0
    WG) wc 2  151  153 5710 /tmp/orders20110505-4469-1qw7fan-0
    Sent file /tmp/orders20110505-4469-1qw7fan-0 (0.2ms)
    Completed 200 OK in 126ms

**Comment by leikind** [comment]
As you see, in production the file with the csv data is not empty. When the tempfile is closed, buffers are flushed and the file is there, 5710 bytes both in production and development.  This is on line logger.debug('WG) wc 2 ' + `wc #{temp_filename}`). The next line and the last line executed inside wice_grid is actually sending the file (send_file). What can go wrong between these two lines, es ist mir ein Rätsel :)

What is your production setup, and how is it different from the production environment?

Could you please look at the raw HTTP response headers, for example, by executing the HTTP request by wget --save-headers http://url.to.retrieve.csv, both in dev and prod

**Comment by leikind** [comment]
Any news?

**Comment by leikind** [comment]
I am pretty  sure I know the cause of this behavior. Please try commenting this line off in production.rb:

  config.action_dispatch.x_sendfile_header = "X-Sendfile"

and see if the problem is fixed.

send_file in Rails 3 by default uses headers to have the web server send the file. Thus, this is a separate request and by that time the tempfile might already have been deleted.

Some links:
http://www.novafist.com/2010/09/send_file-sends-0-bytes-to-client-in-rails/
http://stackoverflow.com/questions/3724853/rails-sends-0-byte-files-using-send-file

**Comment by troessner** [comment]
**The setup itself:**

Locally / Remote (Our CI installation): Ubuntu 10.04
Locally I just use "rails c", remote it's Apache / Passenger

**Headers in development:**

https://gist.github.com/958689

**Headers in production:**

https://gist.github.com/958695

The diff between dev - production is:

https://gist.github.com/958709

**Comment by leikind** [comment]
Ok, the headers prove the case with X-Sendfile. See my previous comment. Commenting line  config.action_dispatch.x_sendfile_header = "X-Sendfile" will solve the problem. This is of course not a good solution because it turns off X-Sendfile for all of the application, but there is no way to configure the behavior of a specific send_file call. I need to find a way to have tempfiles live for a longer time

**Comment by leikind** [comment]
I have created a ticket to address the issue in a better way: https://github.com/leikind/wice_grid/issues/51

**Comment by troessner** [comment]
Great! Thanks a lot for going through that whole bug hunt (let's just call it that, justified or not) with me..:-)
