### ISSUE TITLE
Date Time

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#52]
Hi!

Hello, I'm trying to use :helper_style => :calendar to style my DATETIME filter and it continues with the helper from rails. In filters DATE jQuery works perfectly.

Currently my index.html.erb is thus:
   g.column :column_name => 'Date', :attribute_name => 'date_inicial', :helper_style => :calendar do |ordem_servico|
      [(link_to ordem_servico.data_inicial.to_s_br, edit_ordem_servico_path(ordem_servico)),{:class=>"center"}]
    end

Can you give some tips how to configure your Jquery helper to my DATETIME Filter ? 

Thank u a lot

**Comment by leikind** [comment]
Hello,

The jQuery datepicker plugin only supports dates, so unfortunately wicegrid falls back to the rails helpers

**Comment by leosmeira** [comment]
is it possible to select only the date for the DateTime fields through the DatePicker?

**Comment by leikind** [comment]
No, not at the moment.

**Comment by winterbang** [comment]
`helper_style: :standard` also can't select time and is not  useful for DATETIME fields. I read the [document](http://wicegrid.herokuapp.com/dates?grid%5Bf%5D%5Bupdated_at%5D%5Bfr%5D%5Byear%5D=2011&grid%5Bf%5D%5Bupdated_at%5D%5Bfr%5D%5Bmonth%5D=4&grid%5Bf%5D%5Bupdated_at%5D%5Bfr%5D%5Bday%5D=5), and get the way. why it is impossible for me
