### ISSUE TITLE
Select Date to DateTime field ?

### ISSUE THREAD

**Issue by leosmeira** [leikind/wice_grid#55]
is it possible to select only the date for the DateTime fields through the DatePicker?

**Comment by leikind** [comment]
No, not at the moment

**Comment by leosmeira** [comment]
You can compare the date formats to DateTime fields

**Comment by leikind** [comment]
This is obvious but that is not the point. The point is how wicegrid column types are chosen according to the db column type. Find occurrences of @@handled_type here: https://github.com/leikind/wice_grid/blob/rails3/lib/view_columns.rb . This is how every column/filter class registers itself for certain types. If you move

```
@@handled_type[:datetime] = self
@@handled_type[:timestamp] = self
```

from the declaration of ViewColumnDatetime to the declaration of ViewColumnDate, ViewColumnDate will be used for all date and datetime columns. Or you try to modify  @@handled_type at runtime to achieve the same effect

**Comment by leosmeira** [comment]
In lib/, i try to create a path.
But this don't work

class ViewColumnDate.class_eval < ViewColumnDatetime #:nodoc:
    @@handled_type[:datetime] = self
    @@handled_type[:timestamp] = self
end

**Comment by leikind** [comment]
Please try putting the class definition inside  module Wice ; ; end

Also make sure that this code is evaluated after the gem is loaded.

**Comment by leosmeira** [comment]
I copy the file to "lib/wice_grid_jquery-datetime.rb" and make modification.

In the model, i put:
require "lib/wice_grid_jquery-datetime.rb"

It's Work for me.

**Comment by leosmeira** [comment]
The line 33 is incorrect:

cattr_accessor :handled_type
