### ISSUE TITLE
assets pipline in 3.1 problem

### ISSUE THREAD

**Issue by dima4p** [leikind/wice_grid#59]
In 3.1 rails project putting icons to the app/assets cannot send expand.png icons while keeping them in public does not deliver another. I detected by now only one file in the first set: expand.png.
Additionally it would be great if the generator recognizes the use of assets pipeline and places the assets to the proper place.
By now I have to keep two sets of icons

**Comment by dima4p** [comment]
Additionally  no widgets for date filter are shown

**Comment by dima4p** [comment]
here is the html generated:
&lt;th>&lt;div class="date-filter">&lt;span id="grid_f_applied_from_fr_date_placeholder">&lt;input id="grid_f_applied_from_fr" name="grid[f][applied_from][fr]" type="hidden" value="" /> &lt;a class="date_label" href="#" onclick=" $('#grid_f_applied_from_fr_date_view').html(''); $('#grid_f_applied_from_fr')[0].value = ''; ; return false;" title="Кликните, чтобы удалить дату">&lt;span id="grid_f_applied_from_fr_date_view">&lt;/span>&lt;/a>&lt;/span>&lt;br/>&lt;span id="grid_f_applied_from_to_date_placeholder">&lt;input id="grid_f_applied_from_to" name="grid[f][applied_from][to]" type="hidden" value="" /> &lt;a class="date_label" href="#" onclick=" $('#grid_f_applied_from_to_date_view').html(''); $('#grid_f_applied_from_to')[0].value = ''; ; return false;" title="Кликните, чтобы удалить дату">&lt;span id="grid_f_applied_from_to_date_view">&lt;/span>&lt;/a>&lt;/span>&lt;/div>&lt;/th>

**Comment by leikind** [comment]
see 3.2.0.pre4
