### ISSUE TITLE
A sample query that does not work

### ISSUE THREAD

**Issue by mikhailian** [leikind/wice_grid#6]
http://grid.leikind.org/basics5?grid[f][created_at][fr]=2009-10-01 16%3A56&grid[f][created_at][to]=2009-10-31 16%3A56

**Comment by leikind** [comment]
found the reason, created this ticket: http://github.com/leikind/wice_grid/issues/#issue/7
Closing this one

**Comment by leikind** [comment]
http://github.com/leikind/wice_grid/commit/6c9e88091b417df7a3ba32439c500a38404eaeda
