### ISSUE TITLE
Option yearRange is needed for datepicker

### ISSUE THREAD

**Issue by dima4p** [leikind/wice_grid#61]
And most probably for the portotype version.
You see, it is strange to have the range 2001..2021 for the birthday year of the user.

**Comment by leikind** [comment]
any ideas about the API and the way it should look like?

**Comment by dima4p** [comment]
I think, the option for #column should be created. I suggest to make it indifferent on the java-script used, will it be datepicker, calendarview, or something else. It should take the hash that is to be translated to JS object and passed to the JS call.
It may be named :js_options, so in my case it will be like the following for the ruby 1.8:
g.column :attribute_name => 'born_on',
:js_options => {:changeMonth => true, :changeYear => true, :yearRange => '-120:+0', :defaultDate => '-30y'}

**Comment by dima4p** [comment]
P.S. I know you pass changeMonth and changeYear, but maybe someone will want it to be false.

**Comment by leikind** [comment]
The solution is very basic:  https://github.com/leikind/wice_grid/commit/a88a7506b22015137590c40e888b3c68bb005579

There is a default year range for all datepickers in the config file. Providing WiceGrid configuration API to set up  each grid seems redundant when one can easily change the range with javascript:

``` javascript
$( ".hasDatepicker" ).datepicker( "option", "yearRange", "2000:2042" );
```

**Comment by dima4p** [comment]
What if different ranges are needed, say for :date_of_birth and :passport_valid_tilll?

**Comment by leikind** [comment]
Then you use the aforementioned javascript with  DOM IDs to target specific datepickers  . There is no need for additional API when using `datepicker( "option", param, value )` is a perfectly valid _jQuery way_.
