### ISSUE TITLE
Delayed::Job: How to enqueue export

### ISSUE THREAD

**Issue by tomkurt** [leikind/wice_grid#63]
Is it possible to extract ar_options from wice grid without triggering the "all"-query?

Then I could do something like

``` ruby
class ProductsController
  class ExportJob < Struct.new(:ar_option)
    def perform
      ProductMailer.send_products(Product.find(ar_options).to_csv)
    end
  end

  def index
     @grid initialize_grid(Product)
     if @grid.output_csv?
        @grid.render_partial_without_fetching_records
        Delayed::Job.enqueue(ExportJob.new(@grid.ar_options))
  end
end
```

**Comment by leikind** [comment]
ar_options are not formed until the AR find call, in a lazy fashion, after all column definitions have been processed.

**Comment by tomkurt** [comment]
Ok so without hacking their is no methods such as render_partial_without_fetching_records.
