### ISSUE TITLE
Multial link in one column like Show,Edit,Delete doesn't work

### ISSUE THREAD

**Issue by jagdishdasani** [leikind/wice_grid#64]
Multiple links in one single column doesn't work properly only last link is visible to grid

 g.column do |administrator_article|
                            link_to('Show', show,:class => 'previewButton')
                            link_to('Edit', edit,:class => 'editButton')
                            link_to('Destroy', delete, confirm: 'Are you sure?', method: :delete,:class => 'deleteButton')
                         end

is there any way to achieve this??

**Comment by leikind** [comment]
This is what you have written:

``` ruby
def foo
  puts yield
end


foo do
  'hello'
  ' '
  'world'
end
```

Of course it will  return only the last object in the block. Try concatenating strings:

``` ruby

foo do
  'hello' +
  ' ' +
  'world'
end
```

**Comment by jagdishdasani** [comment]
its working fine. thanks buddy.
