### ISSUE TITLE
uninitialized constant Wice::Controller::MissingFile

### ISSUE THREAD

**Issue by bentonbarnett** [leikind/wice_grid#65]
Hello,

I am attempting to set up Wice Grid to export a CSV file an am running into this error:

```
uninitialized constant Wice::Controller::MissingFile
```

Here are the first few lines of the trace. The first two lines are the only lines which mention Wicegrid.

```
wice_grid (3.0.1) lib/wice_grid_controller.rb:168:in `send_file_rails2'
wice_grid (3.0.1) lib/wice_grid_controller.rb:120:in `export_grid_if_requested'
app/controllers/admin_controller.rb:196:in `comp_set_admin'
```

It's throwing the error on Rails 3.0.5 running on Ruby 1.9.2p290. Let me know if there's any more information you need.

**Comment by leikind** [comment]
what's the web server and the rails environment?

**Comment by bentonbarnett** [comment]
The web server is Ubuntu 10.04 LTS, kernel 2.6.32-318-ec2. The Rails environment is development.

Thanks for building this gem, by the way, I think you've done an excellent job. You've added a lot of well thought out features and created a very smart feature set. I've used on several projects and this is the only issue I've had with it.

**Comment by leikind** [comment]
thank you for the kinds words. A big rewrite for Rails 3.2 is on the way.

I meant the web server, is it Apache?

**Comment by bentonbarnett** [comment]
Sorry. It's WEBrick 1.3.1.

**Comment by leikind** [comment]
could you please post the view  where the grid is defined? Completely, the whole file

**Comment by bentonbarnett** [comment]
The grid is defined in it's own partial which looks like: https://gist.github.com/2002837

Incase it's needed, here is the relevant code from the controller: https://gist.github.com/2002854

**Comment by leikind** [comment]
why is there <% , and not <%= ?

**Comment by bentonbarnett** [comment]
That's embarrassing. I've been working in HAML for so long I had forgotten even the basics of ERB. Once I added in the equal sign the export to CSV feature worked fine.

It might be worth considering to have the send_file_rails2 method raise a more helpful error.

Thank you for the help. It was very kind of you to help me out like this.

**Comment by leikind** [comment]
No worries.

There is actually a bug there  - an exception is about to be raised, and the exception class is not found. 
I have already fixed it in my development branch. Thank you.
