### ISSUE TITLE
How can i hide pagination status field for no records.

### ISSUE THREAD

**Issue by jagdishdasani** [leikind/wice_grid#68]
How can i hide pagination status field for no records or zero elements. I dont want to display '0' Pagination status.
can you help me for this ?

**Comment by leikind** [comment]
Unfortunately there is no API for this, you can only try to hack the code. What version are you using?

**Comment by jagdishdasani** [comment]
currently i am using this version 3.0.4

**Comment by leikind** [comment]
if you feel adventurous you might try hacking pagination_panel_content and pagination_info in  lib/helpers/wice_grid_view_helpers.rb
