### ISSUE TITLE
grid is not defined

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#71]
Hello Yuri,

i've updated my wicegrid to rails3 branch and i'm having some problems with the filter.

I've replaced the function 
  <%= button_to_function "Filtrar", submit_grid_javascript(@transacoes_grid) %>
for
   <%= button_to_function "Filtrar", "grid.process()" %>

I didn't find about that on web. 

And now the filter is not runing. Can u give-me some tips ?

thanks !

**Comment by leikind** [comment]
which version of the plugin and rails  are you using

**Comment by fillipenorton** [comment]
I'm using rails 3.2.3
Wicegrid 3.2.0.pre1

**Comment by leikind** [comment]
3.2.0.pre1 is unreleased and a work in progress. Look at the message in capital letters in the README and on the github project homepage: beginning with words "WICE_GRID IS UNDER ACTIVE DEVELOPMENT" You might want to stick with version  3.0.4 for the time being. If you still want to use this unstable version, run 

rails wice_grid:install

include the js assets:
https://github.com/leikind/wice_grid_testbed/blob/master/app/assets/javascripts/application.js

and your external submit buttons are done like this now:
https://github.com/leikind/wice_grid_testbed/blob/master/app/views/detached_filters/index.html.haml

%button.btn.btn-primary.wg-external-submit-button{'data-grid-name' => 'grid'} Submit
      %button.btn.wg-external-reset-button{'data-grid-name' => 'grid'} Reset

That is, you just have to have an input element with class .wg-external-submit-button and with an attribute 'data-grid-name' containing the name of the grid.

**Comment by leikind** [comment]
I hope to release a functional version with docs soon

**Comment by fillipenorton** [comment]
Ok, thank you very much. I've installed the node to compile the JS and appears another problem.
I don't know if you can help me, but...
Do you know this message? this issue you shown on firebug's console:

processorInitializerArguments is null
...essorInitializerArguments[1], processorInitializerArguments[2], processorInitial...

I suspect it happens cause wicegrid

**Comment by leikind** [comment]
That's some WiceGrid problem

**Comment by fillipenorton** [comment]
This version 3.0.4 can be used on rails 3.2.3 ?

**Comment by leikind** [comment]
you will run in a lot of problems with the asset pipeline but you can try, with some hacking it should work. 

This bug that you pasted here is really weird. I have a demo app (https://github.com/leikind/wice_grid_testbed) running on Rails 3.2 and the latest unreleased WiceGrid, and as of today all core functionality works well, only advanced features like saved queries do not work.

If you still have that problem with the latest WiceGrid, you might send the the HTML source of the page, I will take a look and try to undertand what is wrong

**Comment by fillipenorton** [comment]
Well, i have try to manipulate the wice_grid_init.js.coffee to solve this problems but i'm having some troubles.
Like this: 
filterDeclaration.declaration is undefined
templates: filterDeclaration.declaration.templates,

into the code

```
for filterDeclaration in filterDeclarations
  do (filterDeclaration) ->
    gridProcessor.register
      filterName : filterDeclaration.filterName
      detached    : filterDeclaration.detached
      templates   : filterDeclaration.declaration.templates <---- here begins the problem
      ids         : filterDeclaration.declaration.ids
```

it doesn't reach .templates cause filterDeclaration.declaration is undefined
and printing filterDeclarations, shows:

[{"filterName":"Descricao","detached":"false","declaration":{"templates":["grid%5Bf%5D%5Bdescricao%5D="],"ids":["grid_f_descricao"]}},{"filterName":"Valor","detached":"false","declaration":{"templates":["grid%5Bf%5D%5Bvalor%5D%5Bfr%5D=","grid%5Bf%5D%5Bvalor%5D%5Bto%5D="],"ids":["grid_f_valor_fr","grid_f_valor_to"]}},{"filterName":"Ativo","detached":"false","declaration":{"templates":["grid%5Bf%5D%5Bativo%5D%5B%5D="],"ids":["grid_f_ativo"]}}]

Can i do something to solve that ?

**Comment by leikind** [comment]
could you give me the html source of the page somehow?

**Comment by fillipenorton** [comment]
Yes, ok!
That's the main:

```
      <div id="main">
        <div id="content">
          <div id="content_block">
            <div class="message success" id="flash_notice"></div>
            <div class="message error" id="flash_error"></div>
    <h2>Despesas Padronizadas</h2>
```

<p><a href="/despesas_padronizadas/new" class="button novo">Novo</a></p>


<div class="wice-grid-container" id="grid"><div id="grid_title"></div><table  class="table-striped table-bordered table wice-grid"><thead><tr  class="wice-grid-title-row"><th class="sorted"><a href="?grid%5Border%5D=descricao&amp;grid%5Border_direction%5D=desc" class="asc">Descricao</a></th><th><a href="?grid%5Border%5D=valor&amp;grid%5Border_direction%5D=asc">Valor</a></th><th><a href="?grid%5Border%5D=ativo&amp;grid%5Border_direction%5D=asc">Ativo</a></th><th></th></tr><tr  class="wg-filter-row" id="grid_filter_row" ><th class="sorted"><input id="grid_f_descricao" name="grid[f][descricao]" size="8" type="text" value="" /></th><th><input class="range-start" id="grid_f_valor_fr" name="grid[f][valor][fr]" size="3" type="text" /><input class="range-end" id="grid_f_valor_to" name="grid[f][valor][to]" size="3" type="text" /></th><th><div class="custom-dropdown-container"><select class="custom-dropdown" id="grid_f_ativo" name="grid[f][ativo]"><option value="" selected="selected">--</option>
<option value="t">sim</option>
<option value="f">não</option></select></div></th><th class="filter_icons"><div class="submit clickable" id="grid_submit_grid_icon" title="Filtrar"></div> <div class="reset clickable" id="grid_reset_grid_icon" title="Reinicializar"></div></th></tr></thead><tfoot><tr><td colspan="4"> <div class="pagination_status">1-4 / 4 </div></td></tr></tfoot><tbody><tr  class="odd"><td class="sorted esquerda"><a href="/despesas_padronizadas/2/edit">Avaria retrovisor</a></td><td class="direita"><a href="/despesas_padronizadas/2/edit">0,00</a></td><td class="centro"><a href="/despesas_padronizadas/2/edit"><img alt="True" src="/assets/true.png" /></a></td><td></td></tr><tr  class="even"><td class="sorted esquerda"><a href="/despesas_padronizadas/3/edit">Lavagem</a></td><td class="direita"><a href="/despesas_padronizadas/3/edit">0,00</a></td><td class="centro"><a href="/despesas_padronizadas/3/edit"><img alt="True" src="/assets/true.png" /></a></td><td></td></tr><tr  class="odd"><td class="sorted esquerda"><a href="/despesas_padronizadas/1/edit">Perda de documento</a></td><td class="direita"><a href="/despesas_padronizadas/1/edit">0,00</a></td><td class="centro"><a href="/despesas_padronizadas/1/edit"><img alt="True" src="/assets/true.png" /></a></td><td></td></tr><tr  class="even"><td class="sorted esquerda"><a href="/despesas_padronizadas/4/edit">teste</a></td><td class="direita"><a href="/despesas_padronizadas/4/edit">0,00</a></td><td class="centro"><a href="/despesas_padronizadas/4/edit"><img alt="True" src="/assets/true.png" /></a></td><td></td></tr></tbody></table><div class="wg-data" data-filter-declarations="[{&quot;filterName&quot;:&quot;Descricao&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bdescricao%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_descricao&quot;]}},{&quot;filterName&quot;:&quot;Valor&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bvalor%5D%5Bfr%5D=&quot;,&quot;grid%5Bf%5D%5Bvalor%5D%5Bto%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_valor_fr&quot;,&quot;grid_f_valor_to&quot;]}},{&quot;filterName&quot;:&quot;Ativo&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bativo%5D%5B%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_ativo&quot;]}}]" data-processor-initializer-arguments="[&quot;http://localhost:3000/despesas_padronizadas&quot;,&quot;http://localhost:3000/despesas_padronizadas&quot;,&quot;http://localhost:3000/despesas_padronizadas?grid%5Bexport%5D=csv&quot;,&quot;grid%5Bq%5D=&quot;,&quot;grid%5Bfoc%5D=&quot;,&quot;development&quot;]"></div></div><script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
 $('div#grid.wice-grid-container .range-start, .grid_detached_filter .range-start').keyup(function(e, a){
   var endRange = $(e.target).next();
   if (e.target.value){
     endRange.val(0 + parseInt(e.target.value));
     }else{
       endRange.val('');
     }
 });
})
//]]>

</script>


<p><a href="/despesas_padronizadas/new" class="button novo">Novo</a></p>


              </div>

```
    </div>
      </div><!--end main-->
```

**Comment by leikind** [comment]
That is weird. I took the div containing the data saved it as a html page, and wrote some simple javascript that does the same as the javascript in WiceGrid - gets the filterDeclaration.declaration.templates. It works.

Look:

``` html
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
  var dataDiv = $(".wg-data");
  var filterDeclarations = dataDiv.data("filter-declarations");

  for (var i = 0;  i < filterDeclarations.length; i++) {
    filterDeclaration = filterDeclarations[i];
    console.log(filterDeclaration.declaration.templates);
  }

})
//]]>

</script>

</head>
<div class="wg-data" data-filter-declarations="[{&quot;filterName&quot;:&quot;Descricao&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bdescricao%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_descricao&quot;]}},{&quot;filterName&quot;:&quot;Valor&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bvalor%5D%5Bfr%5D=&quot;,&quot;grid%5Bf%5D%5Bvalor%5D%5Bto%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_valor_fr&quot;,&quot;grid_f_valor_to&quot;]}},{&quot;filterName&quot;:&quot;Ativo&quot;,&quot;detached&quot;:&quot;false&quot;,&quot;declaration&quot;:{&quot;templates&quot;:[&quot;grid%5Bf%5D%5Bativo%5D%5B%5D=&quot;],&quot;ids&quot;:[&quot;grid_f_ativo&quot;]}}]" data-processor-initializer-arguments="[&quot;http://localhost:3000/despesas_padronizadas&quot;,&quot;http://localhost:3000/despesas_padronizadas&quot;,&quot;http://localhost:3000/despesas_padronizadas?grid%5Bexport%5D=csv&quot;,&quot;grid%5Bq%5D=&quot;,&quot;grid%5Bfoc%5D=&quot;,&quot;development&quot;]"></div>
</html>

```

Load the page and look in the js console - it works.

**Comment by leikind** [comment]
do you have the page in public access?

**Comment by fillipenorton** [comment]
No, i dont't have, this branch is local. The version online doesn't have actual wicegrid.

I'll test this page you send me

**Comment by fillipenorton** [comment]
Hey Yuri,

after your last comment, i keep trying to solve my problem and with the help of my friend managed to solve the problem

We just changed a few things:

```
processorInitializerArguments = JSON.parse(dataDiv.attr("data-processor-initializer-arguments"))

filterDeclarations = JSON.parse(dataDiv.attr("data-filter-declarations"))
```

on wice_grid_init.js.coffee

dataDiv.attr("data-processor-initializer-arguments") was returning a poor string, and we need the structure of Key => Value

thanks for your attetion

**Comment by leikind** [comment]
this is weird. Thanks for the report. I will take a closer look at that chunk of code.
