### ISSUE TITLE
pagination style

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#73]
Hey buddy!

Where can i find the css archive of style of the pagination ?

Its desconfigure here! 

Thanks

**Comment by leikind** [comment]
Sorry, I don't understand. What archive?

**Comment by fillipenorton** [comment]
Something break on pagination CSS, i need to fix it!

this is the Code:

<div class="pagination">
<ul>
<li class="disabled">
<li class="active">
<li>
<li>
</ul>
</div>

**Comment by leikind** [comment]
I dont see the code. Use chrome or safari web inspector to see what is wrong

**Comment by fillipenorton** [comment]
I explained so confusing but I managed to solve the problem.

Thanks! closing Issue!
