### ISSUE TITLE
Error installing wice_grid

### ISSUE THREAD

**Issue by pboettcher** [leikind/wice_grid#76]
D:\Work>bundle install
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/..
Using rake (0.9.2.2)
Using i18n (0.6.1)
Using multi_json (1.3.6)
Using activesupport (3.2.1)
Using builder (3.0.2)
Using activemodel (3.2.1)
Using erubis (2.7.0)
Using journey (1.0.4)
Using rack (1.4.1)
Using rack-cache (1.2)
Using rack-test (0.6.1)
Using hike (1.2.1)
Using tilt (1.3.3)
Using sprockets (2.1.3)
Using actionpack (3.2.1)
Using mime-types (1.19)
Using polyglot (0.3.3)
Using treetop (1.4.10)
Using mail (2.4.4)
Using actionmailer (3.2.1)
Using arel (3.0.2)
Using tzinfo (0.3.33)
Using activerecord (3.2.1)
Using activeresource (3.2.1)
Using gyoku (0.4.6)
Using nokogiri (1.5.5)
Using akami (1.2.0)
Using bcrypt-ruby (3.0.1)
Using bundler (1.1.3)
Using coffee-script-source (1.3.3)
Using execjs (1.4.0)
Using coffee-script (2.2.0)
Using rack-ssl (1.3.2)
Using json (1.7.5)
Using rdoc (3.12)
Using thor (0.14.6)
Using railties (3.2.1)
Using coffee-rails (3.2.2)
Using orm_adapter (0.0.7)
Using warden (1.1.1)
Using devise (2.0.4)
Using httpi (1.1.1)
Using nori (1.1.3)
Using wasabi (2.5.1)
Using savon (1.1.0)
Using dhl-intraship (0.2.0)
Using ffi (1.0.9)
Using jquery-rails (2.1.2)
Using jquery-ui-rails (2.0.0)
Using pg (0.13.2)
Using rails (3.2.1)
Using sass (3.2.1)
Using sass-rails (3.2.5)
Using typhoeus (0.4.2)
Using uglifier (1.3.0)
Using usps (0.1.2)
Installing wice_grid (3.2.0.pre1)
Your bundle is complete! Use 'bundle show [gemname]' to see where a bundled gem is installed.

D:\Work>rails g wice_grid:install
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in 'r
equire': cannot load such file -- will_paginate.rb (LoadError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/dependencies
.rb:251:in 'block in require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/dependencies
.rb:236:in 'load_dependency'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.2.1/lib/active_support/dependencies
.rb:251:in 'require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/wice_grid-3.2.0.pre1/lib/wice_grid.rb:3:in '<top (r
equired)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in 'require
'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in 'block (
2 levels) in require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in 'each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in 'block i
n require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in 'each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in 'require'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.1.3/lib/bundler.rb:119:in 'require'
        from D:/Work/Paul/Documents/PROGRAMM/Muztrade/muztrade/config/application.rb:7:in '<top (req
uired)>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.1/lib/rails/commands.rb:24:in 'require
'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/railties-3.2.1/lib/rails/commands.rb:24:in '<top (r
equired)>'
        from script/rails:6:in 'require'
        from script/rails:6:in '<main>'

**Comment by leikind** [comment]
Please use the latest version of the gem: 3.2.0.pre4

**Comment by pboettcher** [comment]
I did exactly as is described in your installing guide. Now I'll try 3.2.0.pre4

**Comment by pboettcher** [comment]
It helped.
