### ISSUE TITLE
undefined method `per' for #<ActiveRecord::Relation:0x007fb25459b178> wice_grid (3.2.0) lib/wice_grid.rb:297:in `block in read'

### ISSUE THREAD

**Issue by ikeqiao** [leikind/wice_grid#77]
my code :
@samples_grid = initialize_grid(Sample.where(usid:"HK-TR182"))

but raise NoMethodError, the exception message as follow:

activerecord (3.2.8) lib/active_record/relation/delegation.rb:45:in method_missing'
wice_grid (3.2.0) lib/wice_grid.rb:297:inblock in read'
activerecord (3.2.8) lib/active_record/scoping/default.rb:41:in block in unscoped'
activerecord (3.2.8) lib/active_record/relation.rb:241:inblock in scoping'
activerecord (3.2.8) lib/active_record/scoping.rb:98:in with_scope'
activerecord (3.2.8) lib/active_record/relation.rb:241:inscoping'
activerecord (3.2.8) lib/active_record/scoping/default.rb:41:in unscoped'
wice_grid (3.2.0) lib/wice_grid.rb:286:inread'
wice_grid (3.2.0) lib/wice_grid.rb:325:in resultset'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:628:inpagination_info'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:585:in pagination_panel_content'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:219:inblock in grid_html'
wice_grid (3.2.0) lib/grid_renderer.rb:99:in pagination_panel'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:217:ingrid_html'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:126:in define_grid'
wice_grid (3.2.0) lib/helpers/wice_grid_view_helpers.rb:76:ingrid'
app/views/samples/_grid.html.erb:3:in _app_views_samples__grid_html_erb___2161134573340366962_70201971797100'
actionpack (3.2.8) lib/action_view/template.rb:145:inblock in render'
activesupport (3.2.8) lib/active_support/notifications.rb:125:in instrument'
actionpack (3.2.8) lib/action_view/template.rb:143:inrender'

ruby &rails verion:
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.0]
Rails 3.2.8

**Comment by leikind** [comment]
could you please post your Gemfile.lock using the Markdown markup?

**Comment by ikeqiao** [comment]
<p>Gemfile.lock</p>

<pre>
<code>
GEM
  remote: http://ruby.taobao.org/
  specs:
    Ascii85 (1.0.2)
    actionmailer (3.2.8)
      actionpack (= 3.2.8)
      mail (~> 2.4.4)
    actionpack (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.0)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.1.3)
    activemodel (3.2.8)
      activesupport (= 3.2.8)
      builder (~> 3.0.0)
    activerecord (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
    activesupport (3.2.8)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    acts-as-taggable-on (2.3.3)
      rails (~> 3.0)
    addressable (2.3.2)
    annotate (2.5.0)
      rake
    arel (3.0.2)
    barby (0.5.0)
    bcrypt-ruby (3.0.1)
    bootstrap-sass (2.0.4.0)
    bootstrap-will_paginate (0.0.6)
      will_paginate
    builder (3.0.4)
    cancan (1.6.8)
    capybara (1.1.3)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      selenium-webdriver (~> 2.0)
      xpath (~> 0.1.4)
    carrierwave (0.6.2)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
    childprocess (0.3.6)
      ffi (~> 1.0, >= 1.0.6)
    chunky_png (1.2.6)
    coderay (1.0.8)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.4.0)
    compass (0.12.2)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)
    compass-rails (1.0.3)
      compass (>= 0.12.2, < 0.14)
    devise (2.1.0)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.0.7)
      railties (~> 3.1)
      warden (~> 1.1.1)
    diff-lcs (1.1.3)
    erubis (2.7.0)
    execjs (1.4.0)
      multi_json (~> 1.0)
    factory_girl (2.3.2)
      activesupport
    factory_girl_rails (1.4.0)
      factory_girl (~> 2.3.0)
      railties (>= 3.0.0)
    faker (1.0.1)
      i18n (~> 0.4)
    ffi (1.1.5)
    fssm (0.2.9)
    growl (1.0.3)
    guard (1.5.4)
      listen (>= 0.4.2)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-rspec (0.5.5)
      guard (>= 0.8.4)
    guard-spork (0.3.2)
      guard (>= 0.8.4)
      spork (>= 0.8.4)
    hashery (2.0.1)
    hike (1.2.1)
    i18n (0.6.1)
    journey (1.0.4)
    jquery-rails (2.1.3)
      railties (>= 3.1.0, < 5.0)
      thor (~> 0.14)
    json (1.7.5)
    kaminari (0.14.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    libwebsocket (0.1.5)
      addressable
    listen (0.5.3)
    lumberjack (1.0.2)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    method_source (0.8.1)
    mime-types (1.19)
    mini_magick (3.3)
      subexec (~> 0.1.0)
    multi_json (1.3.7)
    nokogiri (1.5.5)
    orm_adapter (0.0.7)
    pdf-reader (1.2.0)
      Ascii85 (~> 1.0.0)
      hashery (~> 2.0)
      ruby-rc4
    polyglot (0.3.3)
    prawn (1.0.0.rc1)
      pdf-reader (>= 0.9.0)
      ttfunk (~> 1.0.3)
    pry (0.9.10)
      coderay (~> 1.0.5)
      method_source (~> 0.8)
      slop (~> 3.3.1)
    rack (1.4.1)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-ssl (1.3.2)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.8)
      actionmailer (= 3.2.8)
      actionpack (= 3.2.8)
      activerecord (= 3.2.8)
      activeresource (= 3.2.8)
      activesupport (= 3.2.8)
      bundler (~> 1.0)
      railties (= 3.2.8)
    rails-i18n (0.1.8)
      i18n (~> 0.5)
    railties (3.2.8)
      actionpack (= 3.2.8)
      activesupport (= 3.2.8)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.0.0)
    rb-fsevent (0.9.1)
    rdoc (3.12)
      json (~> 1.4)
    rspec (2.11.0)
      rspec-core (~> 2.11.0)
      rspec-expectations (~> 2.11.0)
      rspec-mocks (~> 2.11.0)
    rspec-core (2.11.1)
    rspec-expectations (2.11.3)
      diff-lcs (~> 1.1.3)
    rspec-mocks (2.11.3)
    rspec-rails (2.11.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec (~> 2.11.0)
    ruby-rc4 (0.1.5)
    rubyzip (0.9.9)
    sass (3.2.3)
    sass-rails (3.2.5)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    selenium-webdriver (2.26.0)
      childprocess (>= 0.2.5)
      libwebsocket (~> 0.1.3)
      multi_json (~> 1.0)
      rubyzip
    settingslogic (2.0.8)
    simple_form (2.0.4)
      actionpack (~> 3.0)
      activemodel (~> 3.0)
    slop (3.3.3)
    spork (0.9.2)
    sprockets (2.1.3)
      hike (~> 1.2)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.5)
    subexec (0.1.0)
    thor (0.16.0)
    tilt (1.3.3)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    ttfunk (1.0.3)
    tzinfo (0.3.35)
    uglifier (1.3.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    warden (1.1.1)
      rack (>= 1.0)
    wice_grid (3.2.0)
      kaminari (>= 0.13.0)
    will_paginate (3.0.3)
    xpath (0.1.4)
      nokogiri (~> 1.3)
PLATFORMS
  ruby
DEPENDENCIES
  acts-as-taggable-on (~> 2.3.1)
  annotate (= 2.5.0)
  barby
  bcrypt-ruby (= 3.0.1)
  bootstrap-sass (= 2.0.4)
  bootstrap-will_paginate (= 0.0.6)
  cancan (~> 1.6.7)
  capybara
  carrierwave (= 0.6.2)
  coffee-rails (~> 3.2.1)
  compass-rails
  devise (= 2.1.0)
  factory_girl_rails (= 1.4.0)
  faker (= 1.0.1)
  growl (= 1.0.3)
  guard-rspec (= 0.5.5)
  guard-spork (= 0.3.2)
  jquery-rails
  mini_magick (= 3.3)
  prawn (= 1.0.0.rc1)
  rails (= 3.2.8)
  rails-i18n (= 0.1.8)
  rb-fsevent (= 0.9.1)
  rspec
  rspec-rails (= 2.11.0)
  sass-rails (~> 3.2.3)
  settingslogic (~> 2.0.6)
  simple_form
  spork (= 0.9.2)
  sqlite3 (= 1.3.5)
  uglifier (>= 1.0.3)
  wice_grid (~> 3.2.0)
  will_paginate (= 3.0.3)
</code>
</pre>

**Comment by leikind** [comment]
Try removing will_paginate from Gemfile, run bundle, restart the app and see if it helps

**Comment by ikeqiao** [comment]
It's work now! thank u very much!
