### ISSUE TITLE
Compatibility with the new anti XSS behaviour in the Edge 

### ISSUE THREAD

**Issue by leikind** [leikind/wice_grid#8]
http://github.com/rails/rails/commit/9415935902f120a9bac0bfce7129725a0db38ed3

**Comment by masterkain** [comment]
please see also http://github.com/rails/rails/commit/cc1ad46eadfad2c617d897927eb4bc0c36e1d033

**Comment by leikind** [comment]
http://github.com/leikind/wice_grid/commit/b63aadc09641b7ffd756a800c7ea71c80c66eb48
