### ISSUE TITLE
How I can use column for filter but to hide column in grid

### ISSUE THREAD

**Issue by bhushangahire** [leikind/wice_grid#80]
How I can use column for filter but to hide column in grid.

I wanted to use a association column for filter but not to show that column in grid.
Can anyone help me out with this. 

If this is not available can you give me pointers I can submit the code changes.

**Comment by leikind** [comment]
do you need to change this filter via the UI dynamically or is it just some static condition?

**Comment by bhushangahire** [comment]
Actually in my case I have a filter for associated model. But I dont want to show that association in the grid result. 

e.g. I have accounts list and its associated with Brands.
Now I want the Brands filter but I want to list only accounts column and not brands. 
But I wanna keep the brands filter.

Is there any provision for above scenario. 

Let me know if the above example is not understood.

**Comment by leikind** [comment]
If you want to _always_ show only a subset of records, use :conditions, see controller code here http://wicegrid.herokuapp.com/basics6 , if you want to be able to change the filter via the UI, I am afraid the only way out is to hide the column with css

**Comment by bhushangahire** [comment]
Ok lets see if I can make any patch. Something like :hide_column => true in columns.

**Comment by leikind** [comment]
you can, but the easiest way would be just to add the style in your own css file

**Comment by bhushangahire** [comment]
But there is not custom class applied for the column how you will hide whole column?

**Comment by leikind** [comment]
you can add any css class to any column https://github.com/leikind/wice_grid/blob/rails3/lib/grid_renderer.rb#L160

**Comment by bhushangahire** [comment]
Humm got it. But its still not applying that html to header.

**Comment by leikind** [comment]
How are you going to hide a column only partially?

**Comment by bhushangahire** [comment]
No I wanna hide the whole column with header. When you add html to column it only applying for the grid records and not the header.

**Comment by leikind** [comment]
That's a bug

**Comment by bhushangahire** [comment]
:) ok will see if I can fix the same or else let me know if you can fix it immediately?

**Comment by leikind** [comment]
no i can't

**Comment by bhushangahire** [comment]
Ok will see if I can make a fix...

**Comment by leikind** [comment]
fixed in 3.2.1.pre1
