### ISSUE TITLE
Ability to turn off "wice_grid.js not loaded" message

### ISSUE THREAD

**Issue by asgeo1** [leikind/wice_grid#82]
I like to load my JS assets at the bottom of my page, not in the head.

If I do that, then I get a JS error from the following code wicegrid inserts mid-way into the page:

```
//<![CDATA[
$(document).ready(function(){ 
  if (typeof(WiceGridProcessor) == "undefined"){
    alert("wice_grid.js not loaded, WiceGrid cannot proceed!\n" +
      "Make sure that you have loaded wice_grid.js.\n" +
      "Add line\n//= require wice_grid.js\n" +
      "to app/assets/javascripts/application.js")
    }
  }) 
//]]>
```

because "$ is undefined".

I know it only inserts this message in development, but it's still annoying.

Could you put a setting in somewhere so it can be turned off?

**Comment by leikind** [comment]
I think the correct solution would be to rewrite $(document).ready in plain javascript without jQuery

**Comment by leikind** [comment]
Please verify if version 3.2.1.pre3 fixes the problem  http://rubygems.org/gems/wice_grid/versions/3.2.1.pre3

**Comment by webchi** [comment]
Still have this error at 3.6.0.pre4
