### ISSUE TITLE
Compatibility with Bootstrap-Datepicker

### ISSUE THREAD

**Issue by jbwl** [leikind/wice_grid#85]
Would it be possible to make Wice Grid compatible with this Bootstrap-ready date picker?

http://www.eyecon.ro/bootstrap-datepicker/

So far, no visually matching datepicker option exists in JQueryUI for Bootstrap, so this would be the best visual match.

**Comment by leikind** [comment]
Looks good. 

But though the markup generated by WiceGrid is compatible with twitter bootstrap by default, it is not a plugin for twitter bootstrap and it should be possible to use WiceGrid in other contexts. The ideal solution would be to support both datepickers. Internally in WiceGrid there is a concept of a column module which defines the UI for the filter, the HTTP parameters and how these HTTP parameters are transformed into conditions. There could be two different column modules for these two different datepickers.

Having said that, I can't say when this will be done, my priorities are lying  elsewhere these days. Also, there is a feature for WIceGrid which is more important and is a real game-changer and will implemented for version 3.2.2 before this one.

**Comment by jbwl** [comment]
Thank you for your answer. I hope you can offer a unified Datepicker API someday. Looking forward for 3.2.2 (now you have my attention ;-) )

**Comment by patie** [comment]
+1

**Comment by lafeber** [comment]
+1

**Comment by nedden** [comment]
+1

**Comment by leikind** [comment]
done
