### ISSUE TITLE
Wice_grid v3.2.1 => column_action.rb is expected to define ViewColumnAction!

### ISSUE THREAD

**Issue by leosmeira** [leikind/wice_grid#87]
Wice_grid v3.2.1
Rails v3.2.11
Ruby v1.8.7 patchlevel 357

=> Error Description:

Exception RuntimeError in PhusionPassenger::Rack::ApplicationSpawner (column_action.rb is expected to define ViewColumnAction!) (process 8578, thread #Thread:0xb77411b8):
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:38:in `build_table_of_processors'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/ordered_hash.rb:162:in`each'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/ordered_hash.rb:162:in `each'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:33:in`build_table_of_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:30:in `tap'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:30:in`build_table_of_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:13:in `load_column_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/wice_grid.rb:48
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in`instance_eval'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:26:in`on_load'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in`on_load'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/wice_grid.rb:39
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:30:in`run'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `run_initializers'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:54:in`each'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/application.rb:136:in`initialize!'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `send'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /mnt/hgfs/Projetos/sites/Imobiliária_NOVO/codigo_site/config/environment.rb:5
    from config.ru:3:in `require'
    from config.ru:3
    from /home/rails_3/.gems/gems/rack-1.4.4/lib/rack/builder.rb:51:in`instance_eval'
    from /home/rails_3/.gems/gems/rack-1.4.4/lib/rack/builder.rb:51:in `initialize'
    from config.ru:1:in`new'
    from config.ru:1
Connecting to database specified by database.yml
[ pid=8578 thr=-608565028 file=utils.rb:176 time=2013-02-08 10:33:44.680 ]: **\* Exception RuntimeError in PhusionPassenger::Rack::ApplicationSpawner (column_action.rb is expected to define ViewColumnAction!) (process 8578, thread #Thread:0xb77411b8):
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:38:in `build_table_of_processors'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/ordered_hash.rb:162:in`each'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/ordered_hash.rb:162:in `each'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:33:in`build_table_of_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:30:in `tap'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:30:in`build_table_of_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/columns.rb:13:in `load_column_processors'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/wice_grid.rb:48
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in`instance_eval'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:26:in`on_load'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from /home/rails_3/.gems/gems/activesupport-3.2.11/lib/active_support/lazy_load_hooks.rb:25:in`on_load'
    from /home/rails_3/.gems/gems/wice_grid-3.2.1/lib/wice_grid.rb:39
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:30:in`run'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:55:in `run_initializers'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:54:in`each'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/application.rb:136:in`initialize!'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in `send'
    from /home/rails_3/.gems/gems/railties-3.2.11/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /mnt/hgfs/Projetos/sites/Imobiliária_NOVO/codigo_site/config/environment.rb:5
    from config.ru:3:in `require'
    from config.ru:3
    from /home/rails_3/.gems/gems/rack-1.4.4/lib/rack/builder.rb:51:in`instance_eval'
    from /home/rails_3/.gems/gems/rack-1.4.4/lib/rack/builder.rb:51:in `initialize'
    from config.ru:1:in`new'
    from config.ru:1

**Comment by leikind** [comment]
Please let me know if this problem is still relevant now, because I have not been able to reproduce it.
