### ISSUE TITLE
Saved queries JS

### ISSUE THREAD

**Issue by lucasvel** [leikind/wice_grid#89]
Hi, I got 2 js errors when using saved queries

in [vendor/assets/javascripts/wice_grid_saved_queries_init.js.coffee:91](https://github.com/leikind/wice_grid/blob/rails3/vendor/assets/javascripts/wice_grid_saved_queries_init.js.coffee#L91)
**Uncaught ReferenceError: errorExplanation is not defined** and error messages are not been displayed

``` javascript
$(notificationMessagesDomId).text(errorExplanation)
```

should be 

``` javascript
$(notificationMessagesDomId).text(errorMessages)
```

I'm not using jQuery UI but Twitter Bootstrap so in [vendor/assets/javascripts/wice_grid_saved_queries_init.js.coffee:97](https://github.com/leikind/wice_grid/blob/rails3/vendor/assets/javascripts/wice_grid_saved_queries_init.js.coffee#L97)
**Uncaught TypeError: Object [object Object] has no method 'effect'**

``` javascript
$(queryListId).effect('highlight') 
```

could be 

``` javascript
$(queryListId).effect('highlight') if jQuery.ui
```

Thank you!

**Comment by leikind** [comment]
Fixed ( https://github.com/leikind/wice_grid/commit/69e7052ea0ad300ac31d463d7189a5cc8f896410 ). Thanks. Better late than never :)
