### ISSUE TITLE
Can't skip with default_scope

### ISSUE THREAD

**Issue by huacnlee** [leikind/wice_grid#9]
for example:
class Post < ActiveRecord::Base
  default_scope :conditions => ['state = ?',1]
end

before use wice_grid I found data with this:
Post.send(:with_exclusive_scope) { Post.all }

when I use wice_grid, I must find with this:
initialize_grid(Post)

I have try to this:
Post.send(:with_exclusive_scope) {  initialize_grid(Post) } 
but it's can not skip Post's default_scope

so, I modify you source code like this: 
http://pasite.org/code/279
I add "skip_default_scope" into "options" and default was true, because sometime I used wice_grid in Admin Panel, I want to list all of the records.

**Comment by leikind** [comment]
I will see into this, thank you.

**Comment by leikind** [comment]
With this commit http://github.com/leikind/wice_grid/commit/4380db805b547eda3feeb44551866cccf6131786 WiceGrid can be used in with_exclusive_scope and with_scope block and will follow the current scope context. No additional parameters are needed

**Comment by leikind** [comment]
http://leikind.org/2009/11/15/wicegrid-and-with-scope
