### ISSUE TITLE
Support setting the table caption tag somehow

### ISSUE THREAD

**Issue by gnapse** [leikind/wice_grid#90]
The most obvious way would be to add a method `caption` so the following could be done:

``` ruby
g.grid(@items_grid) do |g|
  g.caption "List of really cool items"
  ...
end
```

or maybe

``` ruby
g.grid(@items_grid, :caption => "List of really cool items") do |g|
  ...
end
```

But I kind of prefer the first option.

**Comment by leikind** [comment]
Or both? :-)

**Comment by gnapse** [comment]
Sure! why not!?

**Comment by leikind** [comment]
Implemented as `g.caption "List of really cool items"`

https://github.com/leikind/wice_grid/commit/c6d47c2e8a3a6d8ae44bc8e12931a0cac56b7483
