### ISSUE TITLE
group_by: array issue?

### ISSUE THREAD

**Issue by ShawnArnwine** [leikind/wice_grid#91]
I'm attempting to perform a group_by,

Actually using the below code, it is possible to group the records.
all_records = all_records.all.group_by{|t| t.client_name} 

but wice_grid doesn't seem to like an array. It only accepts either activerecord relation or the model name itself. It gives following error:
WiceGrid: ActiveRecord model class (second argument) must be a Class derived from ActiveRecord::Base

Can anyone suggest how I may accomplish this?  Thanks.

**Comment by leikind** [comment]
As it is written in the documentation, "WiceGrid does not take a collection as an input, it works directly with ActiveRecord." Its goal is to form an SQL query, render the resultset in the grid, and provide ways to filter the resultset, that is, again, forming an SQL query

**Comment by ShawnArnwine** [comment]
Understood.  using group_by returns a collection.  I checked if there were other means to do so, but haven't found a way yet.
