### ISSUE TITLE
header_tr_html doesn't pass text-align attribute properly

### ISSUE THREAD

**Issue by hayona-zz** [leikind/wice_grid#92]
Hi,

1st - awesome plugin! save me huge amount of time. KUDOS!
2nd - i'm trying to align the headers text to the right or center w/o any success. 

1st line of _grid.html.erb:
   grid(@jobs_grid, html: {class: 'my-grid'}, header_tr_html:  {class: 'my-header'}) do |g|

css definitions:
table.my-grid {
}

table.my-grid tr.my-header {
   text-align: right;
}

BTW, the infrastructure is OK. for example I successfully changed the background to red by adding this to table.my-grid tr.my-header
 background: red.

it is just something with the text-align i'm missing or is broken :(

cheers

**Comment by leikind** [comment]
So, do you see class `my-header` in the html source?

**Comment by hayona-zz** [comment]
Yes:

<style>
  /*<![CDATA[*/
    .ContactImage{
      display: inline-block;
      width: 50px;
      height: 50px;
      background: url('/assets/contact.png')
    }
    .ContactImage.hover{
      text-underline: none
    }
    
    table.my-grid {
    }
    
    table.my-grid tr.my-header {
      text-align: right;
    }
  /*]]>*/
</style>

<div class='well'>
<h2>Jobs</h2>
</div>

<div class='row-fluid'>
<div class='span12'>
<div class="wice-grid-container" id="grid"><div id="grid_title"></div><table  class="table-striped table-bordered table wice-grid my-grid"><thead><tr  class="wice-grid-title-row my-header"><th><a href="?grid%5Border%5D=id&amp;grid%5Border_direction%5D=asc">Id</a></th><th><a href="?grid%5Border%5D=title&amp;grid%5Border_direction%5D=asc">Title</a></th><th><a href="?grid%5Border%5D=companies.name&amp;grid%5Border_direction%5D=asc">Compnay</a></th><th><a href="?grid%5Border%5D=cities.name&amp;grid%5Border_direction%5D=asc">City</a></th><th><a href="?grid%5Border%5D=cities.area&amp;grid%5Border_direction%5D=asc">Area</a></th><th><a href="?grid%5Border%5D=created_at&amp;grid%5Border_direction%5D=asc">Upload date</a></th><th><a href="?grid%5Border%5D=disciplines.name&amp;grid%5Border_direction%5D=asc">Disciplines</a></th><th>Contact</th><th></th><th></th></tr><tr  class="wg-filter-row my-header" id="grid_filter_row" ><th><input class="range-start" id="grid_f_id_eq" name="grid[f][id][eq]" size="3" type="text" /></th><th><input id="grid_f_title" name="grid[f][title]" size="8" type="text" value="" /></th><th><div class="custom-dropdown-container"><select class="custom-dropdown" id="grid_f_companies_name" name="grid[f][companies.name][]"><option value="" selected="selected">--</option>

**Comment by hayona-zz** [comment]
![image](https://f.cloud.github.com/assets/2781560/361615/45f7e268-a1c9-11e2-9061-4d6f46e2bd26.png)

**Comment by leikind** [comment]
well then, what exactly is a problem? WiceGrid does what it should do, the rest is figuring out with chrome developer tools why your styles do not work. I think you should be defining styles for th, not tr.

**Comment by hayona-zz** [comment]
Yes, WiceGrid is perfect.
My mistake, Rails newbie...
Thanks!

**Comment by leikind** [comment]
Good luck :)
