### ISSUE TITLE
Insert a </br> or new line into a column

### ISSUE THREAD

**Issue by Austio** [leikind/wice_grid#93]
Hey All, I'm trying to put a multi-line response inside of a column.  I am unable to get it to actually put the new line inside of the column though, i've tried this with all permutations of single and double quotes for created the new line.  I've also read through the source code but my ruby-fu isn't strong enough to figure it out.  Any advice?

   g.column name: 'Lead'  do |solicitation|
        solicitation.lead.address_line_1.titlecase + " " + solicitation.lead.address_line_2.titlecase +
          "<\br>"
        solicitation.lead.city.titlecase + ", MO " + solicitation.lead.zip_code
    end

**Comment by leikind** [comment]
Looks like + is missing between "<\br>" and solicitation.lead.city.titlecase

**Comment by Austio** [comment]
Thanks for fast response.  Here is the exact code, i was trying to format it to make it easier to see what the problem was.  I had to escape this with an extra \ or it shows up with just an r in between <>

   g.column name: 'Lead'  do |solicitation|
        solicitation.lead.address_line_1.titlecase + " " + solicitation.lead.address_line_2.titlecase + "<\br>" +
        solicitation.lead.city.titlecase + ", MO " + solicitation.lead.zip_code
    end

Actual output of statement

![WiceGrid](https://f.cloud.github.com/assets/1709860/420513/105c690c-acf1-11e2-9b40-48e6cef39cb2.png)
