### ISSUE TITLE
Reset/Submit Buttons Returning incorrect base path

### ISSUE THREAD

**Issue by Austio** [leikind/wice_grid#94]
Alright, so getting pretty along in wicegrid goodness and pushed my app live with a grid.  

Whenever a submit or reset is submitted it is taking me to the root path of 'unicorn/content' instead of www.myapp.com/content.  However, pagination is working correctly.  Here is the submit button

```
<button class="wg-external-submit-button" data-grid-name="grid">Submit</button>
```

---

After some javascript research in wicegrid i've tracked down the location that i think could be causing this.  

wice_grid_init.js.coffee calls this for the submit

```
setupExternalSubmitReset =  ->
  $(".wg-external-submit-button").each (index, externalSubmitButton) ->
    gridProcessor = getGridProcessorForElement(externalSubmitButton)
    if gridProcessor
      $(externalSubmitButton).click (event) ->
           gridProcessor.process()
           event.preventDefault()
           false
```

Which uses wice_grid_processor.js.coffee.  

First

```
  process : (domIdToFocus)->
     window.location = @buildUrlWithParams(domIdToFocus)
```

Second

```
 buildUrlWithParams : (domIdToFocus)->
   results = new Array()
     jQuery.each(
      @filterDeclarations
        (i, filterDeclaration)=>
          param = @readValuesAndFormQueryString(filterDeclaration.filterName, filterDeclaration.detached, filterDeclaration.templates, filterDeclaration.ids)

          if param && param != ''
            results.push(param)
         )

    res = @baseRequestForFilter
    if  results.length != 0
    allFilterParams = results.join('&')
    res = @appendToUrl(res, allFilterParams)

    if domIdToFocus
      res = @appendToUrl(res, @parameterNameForFocus + domIdToFocus)

   res
```

I think it is not grabbing the base url correctly

**Comment by leikind** [comment]
[irony]
You've just posted the whole code responsible for submitting the grid data. That is ... great. I haven't seen it for a while. Thanks.
[/irony]

Have you tried to debug the execution o the code? Are you sure `gridProcessor` is found? What is the value returned by `buildUrlWithParams` ? Is this page  available publicly?

**Comment by Austio** [comment]
After interfacing with leikind this was related to the unicorn server.  

I had to add these lines in my nginx.conf

 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;

So now full unicorn pass off statement is this.

 location @unicorn {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://unicorn;
  }

**Comment by leikind** [comment]
All's well that ends well :)

Happy coding :)
