### ISSUE TITLE
Css Problem

### ISSUE THREAD

**Issue by basmoura** [leikind/wice_grid#95]
This is how my view is being showing, like there is no css
![screen shot 2013-05-03 at 1 05 12 am](https://f.cloud.github.com/assets/3411986/457572/6b8c4ec6-b3a6-11e2-9508-914d48faf24b.png)

**Comment by leikind** [comment]
Please read the installation section in the README and finish all the steps. https://github.com/leikind/wice_grid#installation

**Comment by basmoura** [comment]
I did it, but i have had to remove the //= require jquery.ui.datepicker line because was generating this issue

Sprockets::FileNotFound in Documentos#index
couldn't find file 'jquery.ui.datepicker'
  (in /Users/basmoura/Development/dpu-se/app/assets/javascripts/application.js:16)

any idea?

**Comment by leikind** [comment]
jQuery Datepicker is part of jQuery UI and has to be installed separately. You didn't, so the file is not found.

Even without it the styles should be present.

Post your application.css. Well formatted.

**Comment by basmoura** [comment]
here is my application.css

/*
- This is a manifest file that'll be compiled into application.css, which will include all the files
- listed below.
  *
- Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
- or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
  *
- You're free to add application-wide styles to this file and they'll appear at the top of the
- compiled file, but it's generally better to create a new file per style scope.
  *
  *= require_self
  *= require_tree .
  */

i made my css in default.css.scss, any problem?

**Comment by leikind** [comment]
Did you run the generator according to the guide?

**Comment by leikind** [comment]
What's in `app/assets/stylesheets/` ?

**Comment by basmoura** [comment]
Yes i did
![screen shot 2013-05-03 at 8 31 20 am](https://f.cloud.github.com/assets/3411986/458715/cf656ebc-b3e4-11e2-95c5-3157e3039b68.png)

**Comment by leikind** [comment]
Check if all the css is loaded.

Also, what exactly do you expect to see, and why is the table as you posted here is wrong?

**Comment by basmoura** [comment]
The css in the http://grid.leikind.org/'s grid is the default css of the gem?

**Comment by leikind** [comment]
Yes and no.

If you use the Twitter Bootstrap css framework, all the markup generated by the plugin is Twitter Bootstrap-ready and will look just like on  http://grid.leikind.org/ . If not, it is up to the application to define the way the table should look like.
