### ISSUE TITLE
Date Range Jquery

### ISSUE THREAD

**Issue by Seaborg** [leikind/wice_grid#97]
Hi,

How can I change default jquery datepicker year range, I've tried:

$('.check-for-datepicker').datepicker({changeYear: true, yearRange : '1990:2010'});

not working.

**Comment by leikind** [comment]
Changing options of an already created datepicker is done differently. Here are the docs: http://api.jqueryui.com/datepicker/#option-yearRange

Also, why is the selector `.check-for-datepicker` ? I don't think WiceGrid generates this markup.

Try this:

``` javascript
$( ".hasDatepicker" ).datepicker( "option", "changeYear", true )  ;  $( ".hasDatepicker" ).datepicker( "option", "yearRange", "2002:2012" );
```

It works for page http://wicegrid.herokuapp.com/dates

**Comment by Seaborg** [comment]
I confirm, this worked out for me, thanks. Excellent gem.
 $( ".hasDatepicker" ).datepicker( "option", "yearRange", "1900:2012" );

**Comment by leikind** [comment]
Thanks. But just to be clear, your question had nothing to do with WiceGrid  :-)
