### ISSUE TITLE
Custom filters for join tables.

### ISSUE THREAD

**Issue by Seaborg** [leikind/wice_grid#99]
In example http://wicegrid.herokuapp.com/joining_tables  how can you filter i.e.:
'Dirk Michaels and Koobus Venter' and have joined result like in the initial table.
Now I can only sort either for Dirk Michaels or Koobus Venter but not both at the same time and result table always shows only single return.
In my project I've got many-to-many relation with :has_many  :through association, I've managed to create table like in the example but can't sort them for joined query like (XXX and YYY).

**Comment by leikind** [comment]
To search for Dirk Michaels or Koobus Venter you will have to use a custom filter with multiple selection.

If you know that `rec.associated_objects` should return both Dirk Michaels or Koobus Venter , but it returns just one, try to force re-initialization of the association:  `rec.associated_objects(true)`

**Comment by leikind** [comment]
http://guides.rubyonrails.org/association_basics.html#controlling-caching

**Comment by leikind** [comment]
Or you could write your own WiceGrid filter :)

**Comment by leikind** [comment]
Custom filters with multiple selection: http://wicegrid.herokuapp.com/custom_filters1
